/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.520 V17.9.0; 5G System; Network Data Analytics Services.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains a data specification.
type DataSubscription struct {
	AmfDataSub   *AmfEventSubscription            `json:"amfDataSub,omitempty" yaml:"amfDataSub" bson:"amfDataSub,omitempty"`
	SmfDataSub   *NsmfEventExposure               `json:"smfDataSub,omitempty" yaml:"smfDataSub" bson:"smfDataSub,omitempty"`
	UdmDataSub   *UdmEeEeSubscription             `json:"udmDataSub,omitempty" yaml:"udmDataSub" bson:"udmDataSub,omitempty"`
	AfDataSub    *AfEventExposureSubsc            `json:"afDataSub,omitempty" yaml:"afDataSub" bson:"afDataSub,omitempty"`
	NefDataSub   *NefEventExposureSubsc           `json:"nefDataSub,omitempty" yaml:"nefDataSub" bson:"nefDataSub,omitempty"`
	NrfDataSub   *NrfNfManagementSubscriptionData `json:"nrfDataSub,omitempty" yaml:"nrfDataSub" bson:"nrfDataSub,omitempty"`
	NsacfDataSub *SacEventSubscription            `json:"nsacfDataSub,omitempty" yaml:"nsacfDataSub" bson:"nsacfDataSub,omitempty"`
}
