/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.504 V17.12.0; 5G System; Unified Data Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.504/
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Container for data which have changed and notification was requested when changed.
type DataChangeNotify struct {
	OriginalCallbackReference []string `json:"originalCallbackReference,omitempty" yaml:"originalCallbackReference" bson:"originalCallbackReference,omitempty"`
	// String represents the SUPI or GPSI
	UeId                          string                          `json:"ueId,omitempty" yaml:"ueId" bson:"ueId,omitempty"`
	NotifyItems                   []NotifyItem                    `json:"notifyItems,omitempty" yaml:"notifyItems" bson:"notifyItems,omitempty"`
	SdmSubscription               *SdmSubscription                `json:"sdmSubscription,omitempty" yaml:"sdmSubscription" bson:"sdmSubscription,omitempty"`
	AdditionalSdmSubscriptions    []SdmSubscription               `json:"additionalSdmSubscriptions,omitempty" yaml:"additionalSdmSubscriptions" bson:"additionalSdmSubscriptions,omitempty"`
	SubscriptionDataSubscriptions []SubscriptionDataSubscriptions `json:"subscriptionDataSubscriptions,omitempty" yaml:"subscriptionDataSubscriptions" bson:"subscriptionDataSubscriptions,omitempty"`
}
