/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.514 V17.9.0; 5G System; Policy Authorization Service; Stage 3.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.514/
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type MpsAction string

// List of MpsAction
const (
	MpsAction_DISABLE_MPS_FOR_DTS              MpsAction = "DISABLE_MPS_FOR_DTS"
	MpsAction_ENABLE_MPS_FOR_DTS               MpsAction = "ENABLE_MPS_FOR_DTS"
	MpsAction_AUTHORIZE_AND_ENABLE_MPS_FOR_DTS MpsAction = "AUTHORIZE_AND_ENABLE_MPS_FOR_DTS"
)
