/*
 * Nudm_EE
 *
 * Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.503 Unified Data Management Services, version 17.10.0
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type RevokedCause string

// List of RevokedCause
const (
	RevokedCause_NOT_ALLOWED         RevokedCause = "NOT_ALLOWED"
	RevokedCause_EXCLUDED_FROM_GROUP RevokedCause = "EXCLUDED_FROM_GROUP"
	RevokedCause_GPSI_REMOVED        RevokedCause = "GPSI_REMOVED"
)
