/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.503 Unified Data Management Services, version 17.13.0
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
 *
 * API version: 2.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package SubscriberDataManagement

// APIClient manages communication with the Nudm_SDM API v2.2.4
// In most cases there should be only one, shared, APIClient.
type APIClient struct {
	cfg    *Configuration
	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// API Services
	AccessAndMobilitySubscriptionDataRetrievalApi   *AccessAndMobilitySubscriptionDataRetrievalApiService
	Class5MBSSubscriptionDataRetrievalApi           *Class5MBSSubscriptionDataRetrievalApiService
	EnhancedCoverageRestrictionDataRetrievalApi     *EnhancedCoverageRestrictionDataRetrievalApiService
	GPSIToSUPITranslationOrSUPIToGPSITranslationApi *GPSIToSUPITranslationOrSUPIToGPSITranslationApiService
	GroupIdentifiersApi                             *GroupIdentifiersApiService
	LCSBroadcastAssistanceDataTypesRetrievalApi     *LCSBroadcastAssistanceDataTypesRetrievalApiService
	LCSMobileOriginatedDataRetrievalApi             *LCSMobileOriginatedDataRetrievalApiService
	LCSPrivacyDataRetrievalApi                      *LCSPrivacyDataRetrievalApiService
	MultipleIdentifiersApi                          *MultipleIdentifiersApiService
	ProseSubscriptionDataRetrievalApi               *ProseSubscriptionDataRetrievalApiService
	ProvidingAcknowledgementOfCAGUpdateApi          *ProvidingAcknowledgementOfCAGUpdateApiService
	ProvidingAcknowledgementOfSNSSAIsUpdateApi      *ProvidingAcknowledgementOfSNSSAIsUpdateApiService
	ProvidingAcknowledgementOfSteeringOfRoamingApi  *ProvidingAcknowledgementOfSteeringOfRoamingApiService
	ProvidingAcknowledgementOfUEParametersUpdateApi *ProvidingAcknowledgementOfUEParametersUpdateApiService
	RetrievalOfMultipleDataSetsApi                  *RetrievalOfMultipleDataSetsApiService
	RetrievalOfSharedDataApi                        *RetrievalOfSharedDataApiService
	RetrievalOfTheIndividualSharedDataApi           *RetrievalOfTheIndividualSharedDataApiService
	SMFSelectionSubscriptionDataRetrievalApi        *SMFSelectionSubscriptionDataRetrievalApiService
	SMSManagementSubscriptionDataRetrievalApi       *SMSManagementSubscriptionDataRetrievalApiService
	SMSSubscriptionDataRetrievalApi                 *SMSSubscriptionDataRetrievalApiService
	SessionManagementSubscriptionDataRetrievalApi   *SessionManagementSubscriptionDataRetrievalApiService
	SliceSelectionSubscriptionDataRetrievalApi      *SliceSelectionSubscriptionDataRetrievalApiService
	SubscriptionCreationApi                         *SubscriptionCreationApiService
	SubscriptionCreationForSharedDataApi            *SubscriptionCreationForSharedDataApiService
	SubscriptionDeletionApi                         *SubscriptionDeletionApiService
	SubscriptionDeletionForSharedDataApi            *SubscriptionDeletionForSharedDataApiService
	SubscriptionModificationApi                     *SubscriptionModificationApiService
	TraceConfigurationDataRetrievalApi              *TraceConfigurationDataRetrievalApiService
	TriggerSORInfoUpdateApi                         *TriggerSORInfoUpdateApiService
	UEContextInAMFDataRetrievalApi                  *UEContextInAMFDataRetrievalApiService
	UEContextInSMFDataRetrievalApi                  *UEContextInSMFDataRetrievalApiService
	UEContextInSMSFDataRetrievalApi                 *UEContextInSMSFDataRetrievalApiService
	UserConsentSubscriptionDataRetrievalApi         *UserConsentSubscriptionDataRetrievalApiService
	V2XSubscriptionDataRetrievalApi                 *V2XSubscriptionDataRetrievalApiService
}

type service struct {
	client *APIClient
}

// NewAPIClient creates a new API client. Requires a userAgent string describing your application.
// optionally a custom http.Client to allow for advanced features such as caching.
func NewAPIClient(cfg *Configuration) *APIClient {
	c := &APIClient{}
	c.cfg = cfg
	c.common.client = c

	// API Services
	c.AccessAndMobilitySubscriptionDataRetrievalApi = (*AccessAndMobilitySubscriptionDataRetrievalApiService)(&c.common)
	c.Class5MBSSubscriptionDataRetrievalApi = (*Class5MBSSubscriptionDataRetrievalApiService)(&c.common)
	c.EnhancedCoverageRestrictionDataRetrievalApi = (*EnhancedCoverageRestrictionDataRetrievalApiService)(&c.common)
	c.GPSIToSUPITranslationOrSUPIToGPSITranslationApi = (*GPSIToSUPITranslationOrSUPIToGPSITranslationApiService)(&c.common)
	c.GroupIdentifiersApi = (*GroupIdentifiersApiService)(&c.common)
	c.LCSBroadcastAssistanceDataTypesRetrievalApi = (*LCSBroadcastAssistanceDataTypesRetrievalApiService)(&c.common)
	c.LCSMobileOriginatedDataRetrievalApi = (*LCSMobileOriginatedDataRetrievalApiService)(&c.common)
	c.LCSPrivacyDataRetrievalApi = (*LCSPrivacyDataRetrievalApiService)(&c.common)
	c.MultipleIdentifiersApi = (*MultipleIdentifiersApiService)(&c.common)
	c.ProseSubscriptionDataRetrievalApi = (*ProseSubscriptionDataRetrievalApiService)(&c.common)
	c.ProvidingAcknowledgementOfCAGUpdateApi = (*ProvidingAcknowledgementOfCAGUpdateApiService)(&c.common)
	c.ProvidingAcknowledgementOfSNSSAIsUpdateApi = (*ProvidingAcknowledgementOfSNSSAIsUpdateApiService)(&c.common)
	c.ProvidingAcknowledgementOfSteeringOfRoamingApi = (*ProvidingAcknowledgementOfSteeringOfRoamingApiService)(&c.common)
	c.ProvidingAcknowledgementOfUEParametersUpdateApi = (*ProvidingAcknowledgementOfUEParametersUpdateApiService)(&c.common)
	c.RetrievalOfMultipleDataSetsApi = (*RetrievalOfMultipleDataSetsApiService)(&c.common)
	c.RetrievalOfSharedDataApi = (*RetrievalOfSharedDataApiService)(&c.common)
	c.RetrievalOfTheIndividualSharedDataApi = (*RetrievalOfTheIndividualSharedDataApiService)(&c.common)
	c.SMFSelectionSubscriptionDataRetrievalApi = (*SMFSelectionSubscriptionDataRetrievalApiService)(&c.common)
	c.SMSManagementSubscriptionDataRetrievalApi = (*SMSManagementSubscriptionDataRetrievalApiService)(&c.common)
	c.SMSSubscriptionDataRetrievalApi = (*SMSSubscriptionDataRetrievalApiService)(&c.common)
	c.SessionManagementSubscriptionDataRetrievalApi = (*SessionManagementSubscriptionDataRetrievalApiService)(&c.common)
	c.SliceSelectionSubscriptionDataRetrievalApi = (*SliceSelectionSubscriptionDataRetrievalApiService)(&c.common)
	c.SubscriptionCreationApi = (*SubscriptionCreationApiService)(&c.common)
	c.SubscriptionCreationForSharedDataApi = (*SubscriptionCreationForSharedDataApiService)(&c.common)
	c.SubscriptionDeletionApi = (*SubscriptionDeletionApiService)(&c.common)
	c.SubscriptionDeletionForSharedDataApi = (*SubscriptionDeletionForSharedDataApiService)(&c.common)
	c.SubscriptionModificationApi = (*SubscriptionModificationApiService)(&c.common)
	c.TraceConfigurationDataRetrievalApi = (*TraceConfigurationDataRetrievalApiService)(&c.common)
	c.TriggerSORInfoUpdateApi = (*TriggerSORInfoUpdateApiService)(&c.common)
	c.UEContextInAMFDataRetrievalApi = (*UEContextInAMFDataRetrievalApiService)(&c.common)
	c.UEContextInSMFDataRetrievalApi = (*UEContextInSMFDataRetrievalApiService)(&c.common)
	c.UEContextInSMSFDataRetrievalApi = (*UEContextInSMSFDataRetrievalApiService)(&c.common)
	c.UserConsentSubscriptionDataRetrievalApi = (*UserConsentSubscriptionDataRetrievalApiService)(&c.common)
	c.V2XSubscriptionDataRetrievalApi = (*V2XSubscriptionDataRetrievalApiService)(&c.common)

	return c
}
