/*
 * LMF Location
 *
 * LMF Location Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.572 V17.10.0; 5G System; Location Management Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.572/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package multimodels

import (
	"errors"
	"reflect"

	"github.com/free5gc/openapi/mediatype/multipart"
	"github.com/free5gc/openapi/models"
)

type DetermineLocationRequestBody struct {
	JsonData                 *models.Lmf_Loc_InputData `json:"jsonData,omitempty"                 multipart:"contentType:application/json"         yaml:"jsonData"                 bson:"jsonData,omitempty"`
	BinaryDataLppMessage     []byte                    `json:"binaryDataLppMessage,omitempty"     multipart:"contentType:application/vnd.3gpp.lpp" yaml:"binaryDataLppMessage"     bson:"binaryDataLppMessage,omitempty"`
	BinaryDataLppMessageExt1 []byte                    `json:"binaryDataLppMessageExt1,omitempty" multipart:"contentType:application/vnd.3gpp.lpp" yaml:"binaryDataLppMessageExt1" bson:"binaryDataLppMessageExt1,omitempty"`
	BinaryDataLppMessageExt2 []byte                    `json:"binaryDataLppMessageExt2,omitempty" multipart:"contentType:application/vnd.3gpp.lpp" yaml:"binaryDataLppMessageExt2" bson:"binaryDataLppMessageExt2,omitempty"`
}

func (c *DetermineLocationRequestBody) ReadFromModels(m *models.DetermineLocationRequestBody) error {
	if m == nil {
		return errors.New("model is nil")
	}
	if m.JsonData == nil {
		return errors.New("jsonData is nil")
	}
	c.JsonData = m.JsonData

	lppDataFields := multipart.GetRelatedContentFields(m, "application/vnd.3gpp.lpp")

	// Update LppMessage
	lppMessage := m.JsonData.LppMessage
	if lppMessage != nil {
		if lppMessage.ContentId == "" {
			return errors.New("lppMessage.ContentId is empty")
		}
		if m.BinaryDataLppMessage == nil {
			return errors.New("BinaryDataLppMessage is nil")
		}
		c.BinaryDataLppMessage = multipart.MatchRelatedContent(lppMessage.ContentId, lppDataFields)
	}

	// Update LppMessageExt
	if len(m.JsonData.LppMessageExt) > 0 {
		lppMessageExt1 := m.JsonData.LppMessageExt[0]
		if lppMessageExt1.ContentId == "" {
			return errors.New("lppMessageExt[0].ContentId is empty")
		}
		if m.BinaryDataLppMessageExt1 == nil {
			return errors.New("BinaryDataLppMessageExt1 is nil")
		}
		c.BinaryDataLppMessageExt1 = multipart.MatchRelatedContent(lppMessageExt1.ContentId, lppDataFields)
	}

	if len(m.JsonData.LppMessageExt) > 1 {
		lppMessageExt2 := m.JsonData.LppMessageExt[1]
		if lppMessageExt2.ContentId == "" {
			return errors.New("lppMessageExt[1].ContentId is empty")
		}
		if m.BinaryDataLppMessageExt2 == nil {
			return errors.New("BinaryDataLppMessageExt2 is nil")
		}
		c.BinaryDataLppMessageExt2 = multipart.MatchRelatedContent(lppMessageExt2.ContentId, lppDataFields)
	}

	return nil
}

func (c *DetermineLocationRequestBody) BuildToModels() (*models.DetermineLocationRequestBody, error) {
	if c == nil {
		return nil, errors.New("model is nil")
	}
	if c.JsonData == nil {
		return nil, errors.New("jsonData is nil")
	}

	m := &models.DetermineLocationRequestBody{}
	m.JsonData = c.JsonData

	lppDataFields := multipart.GetRelatedContentFields(m, "application/vnd.3gpp.lpp")
	lppFieldIndex := 0

	// Update LppMessage
	lppMessage := c.JsonData.LppMessage
	if lppMessage != nil {
		contentId := lppMessage.ContentId
		if contentId == "" {
			return nil, errors.New("lppMessage.ContentId is empty")
		}
		if c.BinaryDataLppMessage == nil {
			return nil, errors.New("BinaryDataLppMessage is nil")
		}
		lppDataFields[lppFieldIndex].Set(reflect.ValueOf(&multipart.RelatedContent{
			ContentID: contentId,
			Content:   c.BinaryDataLppMessage,
		}))
		lppFieldIndex++
	}

	// Update LppMessageExt
	if len(c.JsonData.LppMessageExt) > 0 {
		lppMessageExt1 := c.JsonData.LppMessageExt[0]
		contentId := lppMessageExt1.ContentId
		if contentId == "" {
			return nil, errors.New("lppMessageExt[0].ContentId is empty")
		}
		if c.BinaryDataLppMessageExt1 == nil {
			return nil, errors.New("BinaryDataLppMessageExt1 is nil")
		}
		lppDataFields[lppFieldIndex].Set(reflect.ValueOf(&multipart.RelatedContent{
			ContentID: contentId,
			Content:   c.BinaryDataLppMessageExt1,
		}))
		lppFieldIndex++
	}

	if len(c.JsonData.LppMessageExt) > 1 {
		lppMessageExt2 := c.JsonData.LppMessageExt[1]
		contentId := lppMessageExt2.ContentId
		if contentId == "" {
			return nil, errors.New("lppMessageExt[1].ContentId is empty")
		}
		if c.BinaryDataLppMessageExt2 == nil {
			return nil, errors.New("BinaryDataLppMessageExt2 is nil")
		}
		lppDataFields[lppFieldIndex].Set(reflect.ValueOf(&multipart.RelatedContent{
			ContentID: contentId,
			Content:   c.BinaryDataLppMessageExt2,
		}))
	}

	return m, nil
}
