/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.514 V17.9.0; 5G System; Policy Authorization Service; Stage 3.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.514/
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package PolAuth

import (
	"context"
	"io"
	"net/url"
	"regexp"
	"strings"

	"github.com/free5gc/openapi"

	"github.com/free5gc/openapi/models"
)

// Linger please
var (
	_ context.Context
)

type ApplicationSessionsCollectionApiService service

/*
ApplicationSessionsCollectionApiService Creates a new Individual Application Session Context resource
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param RequestBody - Contains the information for the creation the resource.

@return PostAppSessionsResponse
*/

// PostAppSessionsRequest
type PostAppSessionsRequest struct {
	RequestBody *models.Pcf_PolAuth_AppSessionContext
}

func (r *PostAppSessionsRequest) SetRequestBody(
	RequestBody models.Pcf_PolAuth_AppSessionContext,
) {
	r.RequestBody = &RequestBody
}

type PostAppSessionsResponse struct {
	Location                      string
	Pcf_PolAuth_AppSessionContext *models.Pcf_PolAuth_AppSessionContext
}

type PostAppSessionsError struct {
	Location                           string
	Retry_After                        interface{}
	Pcf_PolAuth_ExtendedProblemDetails *models.Pcf_PolAuth_ExtendedProblemDetails
	ProblemDetails                     *models.ProblemDetails
}

func (a *ApplicationSessionsCollectionApiService) PostAppSessions(
	ctx context.Context,
	request *PostAppSessionsRequest,
) (*PostAppSessionsResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostAppSessionsResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/app-sessions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 201:
		localVarReturnValue.Pcf_PolAuth_AppSessionContext = new(
			models.Pcf_PolAuth_AppSessionContext,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Pcf_PolAuth_AppSessionContext,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		localVarReturnValue.Location = localVarHTTPResponse.Header.Get(
			"Location",
		)
		return &localVarReturnValue, nil
	case 303:
		var v PostAppSessionsError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostAppSessionsError
		v.Pcf_PolAuth_ExtendedProblemDetails = new(
			models.Pcf_PolAuth_ExtendedProblemDetails,
		)
		err = openapi.Deserialize(
			v.Pcf_PolAuth_ExtendedProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Retry_After = localVarHTTPResponse.Header.Get("Retry-After")
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostAppSessionsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

// PostAppSessionsTerminationRequestRequest
type PostAppSessionsTerminationRequestRequest struct {
	RequestBody *models.Pcf_PolAuth_TerminationInfo
}

func (r *PostAppSessionsTerminationRequestRequest) SetRequestBody(
	RequestBody models.Pcf_PolAuth_TerminationInfo,
) {
	r.RequestBody = &RequestBody
}

type PostAppSessionsTerminationRequestResponse struct{}

type PostAppSessionsTerminationRequestError struct {
	Location                 string
	Var3gpp_Sbi_Target_Nf_Id string
	ProblemDetails           *models.ProblemDetails
	RedirectResponse         *models.RedirectResponse
}

func (a *ApplicationSessionsCollectionApiService) PostAppSessionsTerminationRequest(
	ctx context.Context,
	uri string,
	request *PostAppSessionsTerminationRequestRequest,
) (*PostAppSessionsTerminationRequestResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostAppSessionsTerminationRequestResponse
	)

	// create path and map variables
	expression := "{$request.body#/ascReqData/notifUri}/terminate"
	re := regexp.MustCompile(`\{.*\}`)
	localVarPath := re.ReplaceAllString(
		expression,
		uri,
	) // replace bracket {} in the path with the uri

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v PostAppSessionsTerminationRequestError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PostAppSessionsTerminationRequestError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostAppSessionsTerminationRequestError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

// PostAppSessionsEventNotificationRequest
type PostAppSessionsEventNotificationRequest struct {
	RequestBody *models.Pcf_PolAuth_EventsNotification
}

func (r *PostAppSessionsEventNotificationRequest) SetRequestBody(
	RequestBody models.Pcf_PolAuth_EventsNotification,
) {
	r.RequestBody = &RequestBody
}

type PostAppSessionsEventNotificationResponse struct{}

type PostAppSessionsEventNotificationError struct {
	Location                 string
	Var3gpp_Sbi_Target_Nf_Id string
	ProblemDetails           *models.ProblemDetails
	RedirectResponse         *models.RedirectResponse
}

func (a *ApplicationSessionsCollectionApiService) PostAppSessionsEventNotification(
	ctx context.Context,
	uri string,
	request *PostAppSessionsEventNotificationRequest,
) (*PostAppSessionsEventNotificationResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostAppSessionsEventNotificationResponse
	)

	// create path and map variables
	expression := "{$request.body#/ascReqData/evSubsc/notifUri}/notify"
	re := regexp.MustCompile(`\{.*\}`)
	localVarPath := re.ReplaceAllString(
		expression,
		uri,
	) // replace bracket {} in the path with the uri

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v PostAppSessionsEventNotificationError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PostAppSessionsEventNotificationError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostAppSessionsEventNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

// PostAppSessionsDetected5GsBridgeForPduSessionRequest
type PostAppSessionsDetected5GsBridgeForPduSessionRequest struct {
	RequestBody *models.Pcf_PolAuth_PduSessionTsnBridge
}

func (r *PostAppSessionsDetected5GsBridgeForPduSessionRequest) SetRequestBody(
	RequestBody models.Pcf_PolAuth_PduSessionTsnBridge,
) {
	r.RequestBody = &RequestBody
}

type PostAppSessionsDetected5GsBridgeForPduSessionResponse struct{}

type PostAppSessionsDetected5GsBridgeForPduSessionError struct {
	Location                 string
	Var3gpp_Sbi_Target_Nf_Id string
	ProblemDetails           *models.ProblemDetails
	RedirectResponse         *models.RedirectResponse
}

func (a *ApplicationSessionsCollectionApiService) PostAppSessionsDetected5GsBridgeForPduSession(
	ctx context.Context,
	uri string,
	request *PostAppSessionsDetected5GsBridgeForPduSessionRequest,
) (*PostAppSessionsDetected5GsBridgeForPduSessionResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostAppSessionsDetected5GsBridgeForPduSessionResponse
	)

	// create path and map variables
	expression := "{$request.body#/ascReqData/evSubsc/notifUri}/new-bridge"
	re := regexp.MustCompile(`\{.*\}`)
	localVarPath := re.ReplaceAllString(
		expression,
		uri,
	) // replace bracket {} in the path with the uri

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostAppSessionsDetected5GsBridgeForPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

// PostAppSessionsEventNotificationPduSessionRequest
type PostAppSessionsEventNotificationPduSessionRequest struct {
	RequestBody *models.Pcf_PolAuth_PduSessionEventNotification
}

func (r *PostAppSessionsEventNotificationPduSessionRequest) SetRequestBody(
	RequestBody models.Pcf_PolAuth_PduSessionEventNotification,
) {
	r.RequestBody = &RequestBody
}

type PostAppSessionsEventNotificationPduSessionResponse struct{}

type PostAppSessionsEventNotificationPduSessionError struct {
	Location                 string
	Var3gpp_Sbi_Target_Nf_Id string
	ProblemDetails           *models.ProblemDetails
	RedirectResponse         *models.RedirectResponse
}

func (a *ApplicationSessionsCollectionApiService) PostAppSessionsEventNotificationPduSession(
	ctx context.Context,
	uri string,
	request *PostAppSessionsEventNotificationPduSessionRequest,
) (*PostAppSessionsEventNotificationPduSessionResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostAppSessionsEventNotificationPduSessionResponse
	)

	// create path and map variables
	expression := "{$request.body#/ascReqData/evSubsc/notifUri}/pdu-session"
	re := regexp.MustCompile(`\{.*\}`)
	localVarPath := re.ReplaceAllString(
		expression,
		uri,
	) // replace bracket {} in the path with the uri

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v PostAppSessionsEventNotificationPduSessionError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PostAppSessionsEventNotificationPduSessionError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostAppSessionsEventNotificationPduSessionError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}
