/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.504 V17.14.0; 5G System; Unified Data Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.504/
 *
 * API version: 2.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package DR

import (
	"context"
	"io"
	"net/url"
	"strings"

	"github.com/free5gc/openapi"

	"github.com/free5gc/openapi/models"
)

// Linger please
var (
	_ context.Context
)

type PduSessionManagementDataApiService service

/*
PduSessionManagementDataApiService Creates and updates the session management data for a UE and for an individual PDU session
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param UeId - UE id
 * @param PduSessionId - PDU session id
 * @param RequestBody -

@return CreateOrReplaceSessionManagementDataResponse
*/

// CreateOrReplaceSessionManagementDataRequest
type CreateOrReplaceSessionManagementDataRequest struct {
	UeId         *string
	PduSessionId *int32
	RequestBody  *models.Udr_DR_PduSessionManagementData
}

func (r *CreateOrReplaceSessionManagementDataRequest) SetUeId(UeId string) {
	r.UeId = &UeId
}

func (r *CreateOrReplaceSessionManagementDataRequest) SetPduSessionId(
	PduSessionId int32,
) {
	r.PduSessionId = &PduSessionId
}

func (r *CreateOrReplaceSessionManagementDataRequest) SetRequestBody(
	RequestBody models.Udr_DR_PduSessionManagementData,
) {
	r.RequestBody = &RequestBody
}

type CreateOrReplaceSessionManagementDataResponse struct {
	Location                        string
	Udr_DR_PduSessionManagementData *models.Udr_DR_PduSessionManagementData
}

type CreateOrReplaceSessionManagementDataError struct {
	ProblemDetails *models.ProblemDetails
}

func (a *PduSessionManagementDataApiService) CreateOrReplaceSessionManagementData(
	ctx context.Context,
	request *CreateOrReplaceSessionManagementDataRequest,
) (*CreateOrReplaceSessionManagementDataResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Put")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  CreateOrReplaceSessionManagementDataResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/exposure-data/{ueId}/session-management-data/{pduSessionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"ueId"+"}",
		openapi.StringOfValue(*request.UeId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"pduSessionId"+"}",
		openapi.StringOfValue(*request.PduSessionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 201:
		localVarReturnValue.Udr_DR_PduSessionManagementData = new(
			models.Udr_DR_PduSessionManagementData,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Udr_DR_PduSessionManagementData,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		localVarReturnValue.Location = localVarHTTPResponse.Header.Get(
			"Location",
		)
		return &localVarReturnValue, nil
	case 200:
		localVarReturnValue.Udr_DR_PduSessionManagementData = new(
			models.Udr_DR_PduSessionManagementData,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Udr_DR_PduSessionManagementData,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		return &localVarReturnValue, nil
	case 204:
		return &localVarReturnValue, nil
	case 400:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v CreateOrReplaceSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

/*
PduSessionManagementDataApiService Deletes the session management data for a UE and for an individual PDU session
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param UeId - UE id
 * @param PduSessionId - PDU session id

@return DeleteSessionManagementDataResponse
*/

// DeleteSessionManagementDataRequest
type DeleteSessionManagementDataRequest struct {
	UeId         *string
	PduSessionId *int32
}

func (r *DeleteSessionManagementDataRequest) SetUeId(UeId string) {
	r.UeId = &UeId
}

func (r *DeleteSessionManagementDataRequest) SetPduSessionId(
	PduSessionId int32,
) {
	r.PduSessionId = &PduSessionId
}

type DeleteSessionManagementDataResponse struct{}

type DeleteSessionManagementDataError struct {
	ProblemDetails *models.ProblemDetails
}

func (a *PduSessionManagementDataApiService) DeleteSessionManagementData(
	ctx context.Context,
	request *DeleteSessionManagementDataRequest,
) (*DeleteSessionManagementDataResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Delete")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  DeleteSessionManagementDataResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/exposure-data/{ueId}/session-management-data/{pduSessionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"ueId"+"}",
		openapi.StringOfValue(*request.UeId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"pduSessionId"+"}",
		openapi.StringOfValue(*request.PduSessionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 400:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v DeleteSessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

/*
PduSessionManagementDataApiService Retrieves the session management data for a UE and for an individual PDU session
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param UeId - UE id
 * @param PduSessionId - PDU session id
 * @param Ipv4Addr - IPv4 Address of the UE
 * @param Ipv6Prefix - IPv6 Address Prefix of the UE
 * @param Dnn - DNN of the UE
 * @param Fields - attributes to be retrieved
 * @param SuppFeat - Supported Features

@return QuerySessionManagementDataResponse
*/

// QuerySessionManagementDataRequest
type QuerySessionManagementDataRequest struct {
	UeId         *string
	PduSessionId *int32
	Ipv4Addr     *string
	Ipv6Prefix   *string
	Dnn          *string
	Fields       []string
	SuppFeat     *string
}

func (r *QuerySessionManagementDataRequest) SetUeId(UeId string) {
	r.UeId = &UeId
}

func (r *QuerySessionManagementDataRequest) SetPduSessionId(
	PduSessionId int32,
) {
	r.PduSessionId = &PduSessionId
}

func (r *QuerySessionManagementDataRequest) SetIpv4Addr(Ipv4Addr string) {
	r.Ipv4Addr = &Ipv4Addr
}

func (r *QuerySessionManagementDataRequest) SetIpv6Prefix(Ipv6Prefix string) {
	r.Ipv6Prefix = &Ipv6Prefix
}

func (r *QuerySessionManagementDataRequest) SetDnn(Dnn string) {
	r.Dnn = &Dnn
}

func (r *QuerySessionManagementDataRequest) SetFields(Fields []string) {
	r.Fields = Fields
}

func (r *QuerySessionManagementDataRequest) SetSuppFeat(SuppFeat string) {
	r.SuppFeat = &SuppFeat
}

type QuerySessionManagementDataResponse struct {
	Udr_DR_PduSessionManagementData *models.Udr_DR_PduSessionManagementData
}

type QuerySessionManagementDataError struct {
	ProblemDetails *models.ProblemDetails
}

func (a *PduSessionManagementDataApiService) QuerySessionManagementData(
	ctx context.Context,
	request *QuerySessionManagementDataRequest,
) (*QuerySessionManagementDataResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Get")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  QuerySessionManagementDataResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/exposure-data/{ueId}/session-management-data/{pduSessionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"ueId"+"}",
		openapi.StringOfValue(*request.UeId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"pduSessionId"+"}",
		openapi.StringOfValue(*request.PduSessionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if request.Ipv4Addr != nil {
		err := openapi.AddQueryParams(
			&localVarQueryParams,
			"ipv4-addr",
			request.Ipv4Addr,
			"multi",
		)
		if err != nil {
			return nil, err
		}
	}
	if request.Ipv6Prefix != nil {
		err := openapi.AddQueryParams(
			&localVarQueryParams,
			"ipv6-prefix",
			request.Ipv6Prefix,
			"multi",
		)
		if err != nil {
			return nil, err
		}
	}
	if request.Dnn != nil {
		err := openapi.AddQueryParams(
			&localVarQueryParams,
			"dnn",
			request.Dnn,
			"multi",
		)
		if err != nil {
			return nil, err
		}
	}
	if request.Fields != nil {
		if len(request.Fields) < 1 {
			return &localVarReturnValue, openapi.ReportError(
				"Fields must have at least 1 elements",
			)
		}
		err := openapi.AddQueryParams(
			&localVarQueryParams,
			"fields",
			request.Fields,
			"multi",
		)
		if err != nil {
			return nil, err
		}
	}
	if request.SuppFeat != nil {
		err := openapi.AddQueryParams(
			&localVarQueryParams,
			"supp-feat",
			request.SuppFeat,
			"multi",
		)
		if err != nil {
			return nil, err
		}
	}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 200:
		localVarReturnValue.Udr_DR_PduSessionManagementData = new(
			models.Udr_DR_PduSessionManagementData,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Udr_DR_PduSessionManagementData,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		return &localVarReturnValue, nil
	case 400:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 406:
		var v QuerySessionManagementDataError
		apiError.ErrorModel = v
		return nil, apiError
	case 414:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v QuerySessionManagementDataError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}
