/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.502 V17.12.0; 5G System; Session Management Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.502/
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package PDUSess

import (
	"context"
	"io"
	"net/url"
	"regexp"
	"strings"

	"github.com/free5gc/openapi"

	"github.com/free5gc/openapi/models"
)

// Linger please
var (
	_ context.Context
)

type SMContextsCollectionApiService service

/*
SMContextsCollectionApiService Create SM Context
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param RequestBody - representation of the SM context to be created in the SMF

@return PostSmContextsResponse
*/

// PostSmContextsRequest
type PostSmContextsRequest struct {
	RequestBody *models.PostSmContextsRequestBody
}

func (r *PostSmContextsRequest) SetRequestBody(
	RequestBody models.PostSmContextsRequestBody,
) {
	r.RequestBody = &RequestBody
}

type PostSmContextsResponse struct {
	Location                  string
	PostSmContextsResponse201 *models.PostSmContextsResponse201
}

type PostSmContextsError struct {
	Location                      string
	Var3gpp_Sbi_Target_Nf_Id      string
	PostSmContextsResponse400     *models.PostSmContextsResponse400
	PostSmContextsResponse403     *models.PostSmContextsResponse403
	PostSmContextsResponse404     *models.PostSmContextsResponse404
	PostSmContextsResponse500     *models.PostSmContextsResponse500
	PostSmContextsResponse503     *models.PostSmContextsResponse503
	PostSmContextsResponse504     *models.PostSmContextsResponse504
	ProblemDetails                *models.ProblemDetails
	RedirectResponse              *models.RedirectResponse
	Smf_PDUSess_ExtProblemDetails *models.Smf_PDUSess_ExtProblemDetails
}

func (a *SMContextsCollectionApiService) PostSmContexts(
	ctx context.Context,
	request *PostSmContextsRequest,
) (*PostSmContextsResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostSmContextsResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/sm-contexts"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"multipart/related"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"multipart/related",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 201:
		localVarReturnValue.PostSmContextsResponse201 = new(
			models.PostSmContextsResponse201,
		)
		err = openapi.Deserialize(
			localVarReturnValue.PostSmContextsResponse201,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		localVarReturnValue.Location = localVarHTTPResponse.Header.Get(
			"Location",
		)
		return &localVarReturnValue, nil
	case 307:
		var v PostSmContextsError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PostSmContextsError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostSmContextsError
		v.PostSmContextsResponse400 = new(models.PostSmContextsResponse400)
		err = openapi.Deserialize(
			v.PostSmContextsResponse400,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostSmContextsError
		v.PostSmContextsResponse403 = new(models.PostSmContextsResponse403)
		err = openapi.Deserialize(
			v.PostSmContextsResponse403,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostSmContextsError
		v.PostSmContextsResponse404 = new(models.PostSmContextsResponse404)
		err = openapi.Deserialize(
			v.PostSmContextsResponse404,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostSmContextsError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostSmContextsError
		v.Smf_PDUSess_ExtProblemDetails = new(
			models.Smf_PDUSess_ExtProblemDetails,
		)
		err = openapi.Deserialize(
			v.Smf_PDUSess_ExtProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostSmContextsError
		v.Smf_PDUSess_ExtProblemDetails = new(
			models.Smf_PDUSess_ExtProblemDetails,
		)
		err = openapi.Deserialize(
			v.Smf_PDUSess_ExtProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostSmContextsError
		v.Smf_PDUSess_ExtProblemDetails = new(
			models.Smf_PDUSess_ExtProblemDetails,
		)
		err = openapi.Deserialize(
			v.Smf_PDUSess_ExtProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostSmContextsError
		v.PostSmContextsResponse500 = new(models.PostSmContextsResponse500)
		err = openapi.Deserialize(
			v.PostSmContextsResponse500,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostSmContextsError
		v.PostSmContextsResponse503 = new(models.PostSmContextsResponse503)
		err = openapi.Deserialize(
			v.PostSmContextsResponse503,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 504:
		var v PostSmContextsError
		v.PostSmContextsResponse504 = new(models.PostSmContextsResponse504)
		err = openapi.Deserialize(
			v.PostSmContextsResponse504,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

// PostSmContextsSmContextStatusNotificationRequest
type PostSmContextsSmContextStatusNotificationRequest struct {
	RequestBody *models.Smf_PDUSess_SmContextStatusNotification
}

func (r *PostSmContextsSmContextStatusNotificationRequest) SetRequestBody(
	RequestBody models.Smf_PDUSess_SmContextStatusNotification,
) {
	r.RequestBody = &RequestBody
}

type PostSmContextsSmContextStatusNotificationResponse struct{}

type PostSmContextsSmContextStatusNotificationError struct {
	Location                 string
	Var3gpp_Sbi_Target_Nf_Id string
	ProblemDetails           *models.ProblemDetails
	RedirectResponse         *models.RedirectResponse
}

func (a *SMContextsCollectionApiService) PostSmContextsSmContextStatusNotification(
	ctx context.Context,
	uri string,
	request *PostSmContextsSmContextStatusNotificationRequest,
) (*PostSmContextsSmContextStatusNotificationResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Post")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PostSmContextsSmContextStatusNotificationResponse
	)

	// create path and map variables
	expression := "{$request.body#/smContextStatusUri}"
	re := regexp.MustCompile(`\{.*\}`)
	localVarPath := re.ReplaceAllString(
		expression,
		uri,
	) // replace bracket {} in the path with the uri

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v PostSmContextsSmContextStatusNotificationError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PostSmContextsSmContextStatusNotificationError
		v.RedirectResponse = new(models.RedirectResponse)
		err = openapi.Deserialize(
			v.RedirectResponse,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		v.Location = localVarHTTPResponse.Header.Get("Location")
		v.Var3gpp_Sbi_Target_Nf_Id = localVarHTTPResponse.Header.Get(
			"3gpp-Sbi-Target-Nf-Id",
		)
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PostSmContextsSmContextStatusNotificationError
		v.ProblemDetails = new(models.ProblemDetails)
		err = openapi.Deserialize(
			v.ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return &localVarReturnValue, openapi.ReportError(
			"%d is not a valid status code in PostSmContextsSmContextStatusNotification",
			localVarHTTPResponse.StatusCode,
		)
	}
}
