/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.522 V17.7.0; 5G System; Network Exposure Function Northbound APIs.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.522/
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package TrafInfl

import (
	"context"
	"io"
	"net/url"
	"strings"

	"github.com/free5gc/openapi"

	"github.com/free5gc/openapi/models"
)

// Linger please
var (
	_ context.Context
)

type IndividualTrafficInfluenceSubscriptionApiService service

/*
IndividualTrafficInfluenceSubscriptionApiService Deletes an already existing subscription
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param AfId - Identifier of the AF
 * @param SubscriptionId - Identifier of the subscription resource

@return DeleteAnSubscriptionResponse
*/

// DeleteAnSubscriptionRequest
type DeleteAnSubscriptionRequest struct {
	AfId           *string
	SubscriptionId *string
}

func (r *DeleteAnSubscriptionRequest) SetAfId(AfId string) {
	r.AfId = &AfId
}

func (r *DeleteAnSubscriptionRequest) SetSubscriptionId(SubscriptionId string) {
	r.SubscriptionId = &SubscriptionId
}

type DeleteAnSubscriptionResponse struct{}

type DeleteAnSubscriptionError struct {
	Location           string
	Nef_ProblemDetails *models.Nef_ProblemDetails
}

func (a *IndividualTrafficInfluenceSubscriptionApiService) DeleteAnSubscription(
	ctx context.Context,
	request *DeleteAnSubscriptionRequest,
) (*DeleteAnSubscriptionResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Delete")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  DeleteAnSubscriptionResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/{afId}/subscriptions/{subscriptionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"afId"+"}",
		openapi.StringOfValue(*request.AfId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"subscriptionId"+"}",
		openapi.StringOfValue(*request.SubscriptionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v DeleteAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v DeleteAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v DeleteAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

/*
IndividualTrafficInfluenceSubscriptionApiService Fully updates/replaces an existing subscription resource
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param AfId - Identifier of the AF
 * @param SubscriptionId - Identifier of the subscription resource
 * @param RequestBody - Parameters to update/replace the existing subscription

@return FullyUpdateAnSubscriptionResponse
*/

// FullyUpdateAnSubscriptionRequest
type FullyUpdateAnSubscriptionRequest struct {
	AfId           *string
	SubscriptionId *string
	RequestBody    *models.Nef_TrafInfl_TrafficInfluSub
}

func (r *FullyUpdateAnSubscriptionRequest) SetAfId(AfId string) {
	r.AfId = &AfId
}

func (r *FullyUpdateAnSubscriptionRequest) SetSubscriptionId(
	SubscriptionId string,
) {
	r.SubscriptionId = &SubscriptionId
}

func (r *FullyUpdateAnSubscriptionRequest) SetRequestBody(
	RequestBody models.Nef_TrafInfl_TrafficInfluSub,
) {
	r.RequestBody = &RequestBody
}

type FullyUpdateAnSubscriptionResponse struct {
	Nef_TrafInfl_TrafficInfluSub *models.Nef_TrafInfl_TrafficInfluSub
}

type FullyUpdateAnSubscriptionError struct {
	Location           string
	Nef_ProblemDetails *models.Nef_ProblemDetails
}

func (a *IndividualTrafficInfluenceSubscriptionApiService) FullyUpdateAnSubscription(
	ctx context.Context,
	request *FullyUpdateAnSubscriptionRequest,
) (*FullyUpdateAnSubscriptionResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Put")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  FullyUpdateAnSubscriptionResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/{afId}/subscriptions/{subscriptionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"afId"+"}",
		openapi.StringOfValue(*request.AfId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"subscriptionId"+"}",
		openapi.StringOfValue(*request.SubscriptionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 200:
		localVarReturnValue.Nef_TrafInfl_TrafficInfluSub = new(
			models.Nef_TrafInfl_TrafficInfluSub,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Nef_TrafInfl_TrafficInfluSub,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		return &localVarReturnValue, nil
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v FullyUpdateAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v FullyUpdateAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v FullyUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

/*
IndividualTrafficInfluenceSubscriptionApiService Partially updates/replaces an existing subscription resource
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param AfId - Identifier of the AF
 * @param SubscriptionId - Identifier of the subscription resource
 * @param RequestBody -

@return PartialUpdateAnSubscriptionResponse
*/

// PartialUpdateAnSubscriptionRequest
type PartialUpdateAnSubscriptionRequest struct {
	AfId           *string
	SubscriptionId *string
	RequestBody    *models.Nef_TrafInfl_TrafficInfluSubPatch
}

func (r *PartialUpdateAnSubscriptionRequest) SetAfId(AfId string) {
	r.AfId = &AfId
}

func (r *PartialUpdateAnSubscriptionRequest) SetSubscriptionId(
	SubscriptionId string,
) {
	r.SubscriptionId = &SubscriptionId
}

func (r *PartialUpdateAnSubscriptionRequest) SetRequestBody(
	RequestBody models.Nef_TrafInfl_TrafficInfluSubPatch,
) {
	r.RequestBody = &RequestBody
}

type PartialUpdateAnSubscriptionResponse struct {
	Nef_TrafInfl_TrafficInfluSub *models.Nef_TrafInfl_TrafficInfluSub
}

type PartialUpdateAnSubscriptionError struct {
	Location           string
	Nef_ProblemDetails *models.Nef_ProblemDetails
}

func (a *IndividualTrafficInfluenceSubscriptionApiService) PartialUpdateAnSubscription(
	ctx context.Context,
	request *PartialUpdateAnSubscriptionRequest,
) (*PartialUpdateAnSubscriptionResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Patch")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PartialUpdateAnSubscriptionResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/{afId}/subscriptions/{subscriptionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"afId"+"}",
		openapi.StringOfValue(*request.AfId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"subscriptionId"+"}",
		openapi.StringOfValue(*request.SubscriptionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/merge-patch+json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	// body params
	localVarPostBody = request.RequestBody

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 200:
		localVarReturnValue.Nef_TrafInfl_TrafficInfluSub = new(
			models.Nef_TrafInfl_TrafficInfluSub,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Nef_TrafInfl_TrafficInfluSub,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		return &localVarReturnValue, nil
	case 204:
		return &localVarReturnValue, nil
	case 307:
		var v PartialUpdateAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v PartialUpdateAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 411:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 413:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 415:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v PartialUpdateAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}

/*
IndividualTrafficInfluenceSubscriptionApiService read an active subscriptions for the SCS/AS and the subscription Id
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param AfId - Identifier of the AF
 * @param SubscriptionId - Identifier of the subscription resource

@return ReadAnSubscriptionResponse
*/

// ReadAnSubscriptionRequest
type ReadAnSubscriptionRequest struct {
	AfId           *string
	SubscriptionId *string
}

func (r *ReadAnSubscriptionRequest) SetAfId(AfId string) {
	r.AfId = &AfId
}

func (r *ReadAnSubscriptionRequest) SetSubscriptionId(SubscriptionId string) {
	r.SubscriptionId = &SubscriptionId
}

type ReadAnSubscriptionResponse struct {
	Nef_TrafInfl_TrafficInfluSub *models.Nef_TrafInfl_TrafficInfluSub
}

type ReadAnSubscriptionError struct {
	Location           string
	Nef_ProblemDetails *models.Nef_ProblemDetails
}

func (a *IndividualTrafficInfluenceSubscriptionApiService) ReadAnSubscription(
	ctx context.Context,
	request *ReadAnSubscriptionRequest,
) (*ReadAnSubscriptionResponse, error) {
	var (
		localVarHTTPMethod   = strings.ToUpper("Get")
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  ReadAnSubscriptionResponse
	)
	_ = localVarReturnValue

	// create path and map variables
	localVarPath := a.client.cfg.BasePath() + "/{afId}/subscriptions/{subscriptionId}"
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"afId"+"}",
		openapi.StringOfValue(*request.AfId),
	)
	localVarPath = strings.ReplaceAll(
		localVarPath,
		"{"+"subscriptionId"+"}",
		openapi.StringOfValue(*request.SubscriptionId),
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	localVarHTTPContentTypes := []string{"application/json"}

	localVarHeaderParams["Content-Type"] = localVarHTTPContentTypes[0] // use the first content type specified in 'consumes'

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/json",
		"application/problem+json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := strings.Join(localVarHTTPHeaderAccepts, ", ")
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}

	r, err := openapi.PrepareRequest(
		ctx,
		a.client.cfg,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		localVarFormFileName,
		localVarFileName,
		localVarFileBytes,
	)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHTTPResponse == nil {
		return nil, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	if err != nil {
		return nil, err
	}
	err = localVarHTTPResponse.Body.Close()
	if err != nil {
		return nil, err
	}

	apiError := openapi.GenericOpenAPIError{
		RawBody:     localVarBody,
		ErrorStatus: localVarHTTPResponse.StatusCode,
	}
	_ = apiError

	switch localVarHTTPResponse.StatusCode {
	case 200:
		localVarReturnValue.Nef_TrafInfl_TrafficInfluSub = new(
			models.Nef_TrafInfl_TrafficInfluSub,
		)
		err = openapi.Deserialize(
			localVarReturnValue.Nef_TrafInfl_TrafficInfluSub,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		return &localVarReturnValue, nil
	case 307:
		var v ReadAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 308:
		var v ReadAnSubscriptionError
		v.Location = localVarHTTPResponse.Header.Get("Location")
		apiError.ErrorModel = v
		return nil, apiError
	case 400:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 401:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 403:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 404:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 406:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 429:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 500:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	case 503:
		var v ReadAnSubscriptionError
		v.Nef_ProblemDetails = new(models.Nef_ProblemDetails)
		err = openapi.Deserialize(
			v.Nef_ProblemDetails,
			localVarBody,
			localVarHTTPResponse.Header.Get("Content-Type"),
		)
		if err != nil {
			return nil, err
		}
		apiError.ErrorModel = v
		return nil, apiError
	default:
		return nil, apiError
	}
}
