/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.520 V17.9.0; 5G System; Network Data Analytics Services.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

// Represents a report triggered by a subscribed event type
type SacEventReportItem struct {
	EventType  SacEventType   `json:"eventType" yaml:"eventType" bson:"eventType,omitempty"`
	EventState *SacEventState `json:"eventState" yaml:"eventState" bson:"eventState,omitempty"`
	// string with format \"date-time\" as defined in OpenAPI.
	TimeStamp       *time.Time      `json:"timeStamp" yaml:"timeStamp" bson:"timeStamp,omitempty"`
	EventFilter     *Snssai         `json:"eventFilter" yaml:"eventFilter" bson:"eventFilter,omitempty"`
	SliceStautsInfo *SacEventStatus `json:"sliceStautsInfo,omitempty" yaml:"sliceStautsInfo" bson:"sliceStautsInfo,omitempty"`
}
