/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 32.291 V17.9.0: Telecommunication management; Charging management;  5G system, charging service; Stage 3.
 * Url: http://www.3gpp.org/ftp/Specs/archive/32_series/32.291/
 *
 * API version: 3.1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type Chf_ConvCharging_PDUContainerInformation struct {
	// string with format 'date-time' as defined in OpenAPI.
	TimeofFirstUsage *time.Time `json:"timeofFirstUsage,omitempty" yaml:"timeofFirstUsage,omitempty" bson:"timeofFirstUsage,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	TimeofLastUsage *time.Time `json:"timeofLastUsage,omitempty" yaml:"timeofLastUsage,omitempty" bson:"timeofLastUsage,omitempty"`

	QoSInformation *Pcf_SMPolCtrl_QosData `json:"qoSInformation,omitempty" yaml:"qoSInformation,omitempty" bson:"qoSInformation,omitempty"`

	QoSCharacteristics *Pcf_SMPolCtrl_QosCharacteristics `json:"qoSCharacteristics,omitempty" yaml:"qoSCharacteristics,omitempty" bson:"qoSCharacteristics,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	AfChargingIdentifier int32 `json:"afChargingIdentifier,omitempty" yaml:"afChargingIdentifier,omitempty" bson:"afChargingIdentifier,omitempty"`

	// Application provided charging identifier allowing correlation of charging information.
	AfChargingIdString string `json:"afChargingIdString,omitempty" yaml:"afChargingIdString,omitempty" bson:"afChargingIdString,omitempty"`

	UserLocationInformation *UserLocation `json:"userLocationInformation,omitempty" yaml:"userLocationInformation,omitempty" bson:"userLocationInformation,omitempty"`

	// String with format \"time-numoffset\" optionally appended by \"daylightSavingTime\", where  -
	// \"time-numoffset\" shall represent the time zone adjusted for daylight saving time and be
	// encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  -
	// \"daylightSavingTime\" shall represent the adjustment that has been made and shall be
	// encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.   The example is for 8 hours
	// behind UTC, +1 hour adjustment for Daylight Saving Time.
	UetimeZone string `json:"uetimeZone,omitempty" yaml:"uetimeZone,omitempty" bson:"uetimeZone,omitempty"`

	RATType RatType `json:"rATType,omitempty" yaml:"rATType,omitempty" bson:"rATType,omitempty"`

	ServingNodeID []Chf_ConvCharging_ServingNetworkFunctionID `json:"servingNodeID,omitempty" yaml:"servingNodeID,omitempty" bson:"servingNodeID,omitempty"`

	PresenceReportingAreaInformation map[string]PresenceInfo `json:"presenceReportingAreaInformation,omitempty" yaml:"presenceReportingAreaInformation,omitempty" bson:"presenceReportingAreaInformation,omitempty"`

	Var3gppPSDataOffStatus Chf_ConvCharging_3GPPPSDataOffStatus `json:"3gppPSDataOffStatus,omitempty" yaml:"3gppPSDataOffStatus,omitempty" bson:"3gppPSDataOffStatus,omitempty"`

	SponsorIdentity string `json:"sponsorIdentity,omitempty" yaml:"sponsorIdentity,omitempty" bson:"sponsorIdentity,omitempty"`

	ApplicationserviceProviderIdentity string `json:"applicationserviceProviderIdentity,omitempty" yaml:"applicationserviceProviderIdentity,omitempty" bson:"applicationserviceProviderIdentity,omitempty"`

	ChargingRuleBaseName string `json:"chargingRuleBaseName,omitempty" yaml:"chargingRuleBaseName,omitempty" bson:"chargingRuleBaseName,omitempty"`

	MAPDUSteeringFunctionality Pcf_SMPolCtrl_SteeringFunctionality `json:"mAPDUSteeringFunctionality,omitempty" yaml:"mAPDUSteeringFunctionality,omitempty" bson:"mAPDUSteeringFunctionality,omitempty"`

	MAPDUSteeringMode *Pcf_SMPolCtrl_SteeringMode `json:"mAPDUSteeringMode,omitempty" yaml:"mAPDUSteeringMode,omitempty" bson:"mAPDUSteeringMode,omitempty"`

	TrafficForwardingWay Chf_ConvCharging_TrafficForwardingWay `json:"trafficForwardingWay,omitempty" yaml:"trafficForwardingWay,omitempty" bson:"trafficForwardingWay,omitempty"`

	QosMonitoringReport []Chf_ConvCharging_QosMonitoringReport `json:"qosMonitoringReport,omitempty" yaml:"qosMonitoringReport,omitempty" bson:"qosMonitoringReport,omitempty"`
}
