/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.520 V17.9.0; 5G System; Network Data Analytics Services.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Information of an MB-UPF NF Instance
type Nrf_NFMgmt_MbUpfInfo struct {
	SNssaiMbUpfInfoList []Nrf_NFMgmt_SnssaiUpfInfoItem `json:"sNssaiMbUpfInfoList,omitempty" yaml:"sNssaiMbUpfInfoList,omitempty" bson:"sNssaiMbUpfInfoList,omitempty"`

	MbSmfServingArea []string `json:"mbSmfServingArea,omitempty" yaml:"mbSmfServingArea,omitempty" bson:"mbSmfServingArea,omitempty"`

	InterfaceMbUpfInfoList []Nrf_NFMgmt_InterfaceUpfInfoItem `json:"interfaceMbUpfInfoList,omitempty" yaml:"interfaceMbUpfInfoList,omitempty" bson:"interfaceMbUpfInfoList,omitempty"`

	TaiList []Tai `json:"taiList,omitempty" yaml:"taiList,omitempty" bson:"taiList,omitempty"`

	TaiRangeList []Nrf_NFMgmt_TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList,omitempty" bson:"taiRangeList,omitempty"`

	Priority int32 `json:"priority,omitempty" yaml:"priority,omitempty" bson:"priority,omitempty"`

	SupportedPfcpFeatures string `json:"supportedPfcpFeatures,omitempty" yaml:"supportedPfcpFeatures,omitempty" bson:"supportedPfcpFeatures,omitempty"`
}
