/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.502 V17.12.0; 5G System; Session Management Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.502/
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Smf_PDUSess_N4MessageType string

// List of Smf_PDUSess_N4MessageType
const (
	Smf_PDUSess_N4MessageType_EST_REQ Smf_PDUSess_N4MessageType = "PFCP_SES_EST_REQ" // #nosec G101
	Smf_PDUSess_N4MessageType_EST_RSP Smf_PDUSess_N4MessageType = "PFCP_SES_EST_RSP" // #nosec G101
	Smf_PDUSess_N4MessageType_MOD_REQ Smf_PDUSess_N4MessageType = "PFCP_SES_MOD_REQ" // #nosec G101
	Smf_PDUSess_N4MessageType_MOD_RSP Smf_PDUSess_N4MessageType = "PFCP_SES_MOD_RSP" // #nosec G101
	Smf_PDUSess_N4MessageType_DEL_REQ Smf_PDUSess_N4MessageType = "PFCP_SES_DEL_REQ" // #nosec G101
	Smf_PDUSess_N4MessageType_DEL_RSP Smf_PDUSess_N4MessageType = "PFCP_SES_DEL_RSP" // #nosec G101
	Smf_PDUSess_N4MessageType_REP_REQ Smf_PDUSess_N4MessageType = "PFCP_SES_REP_REQ" // #nosec G101
	Smf_PDUSess_N4MessageType_REP_RSP Smf_PDUSess_N4MessageType = "PFCP_SES_REP_RSP" // #nosec G101
)
