/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.562 HSS Services for interworking with IMS, version 17.6.0
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.562/
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains a Service Area Identifier as defined in 3GPP TS 23.003, clause 12.5.
type ServiceAreaId struct {
	PlmnId *PlmnId `json:"plmnId" yaml:"plmnId" bson:"plmnId,omitempty"`
	// Location Area Code.
	Lac string `json:"lac" yaml:"lac" bson:"lac,omitempty"`
	// Service Area Code.
	Sac string `json:"sac" yaml:"sac" bson:"sac,omitempty"`
}
