/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.518 V17.12.0; 5G System; Access and Mobility Management Services
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CollectionPeriodRmmNrMdt string

// List of CollectionPeriodRmmNrMdt
const (
	CollectionPeriodRmmNrMdt_1024  CollectionPeriodRmmNrMdt = "1024"  // #nosec G101
	CollectionPeriodRmmNrMdt_2048  CollectionPeriodRmmNrMdt = "2048"  // #nosec G101
	CollectionPeriodRmmNrMdt_5120  CollectionPeriodRmmNrMdt = "5120"  // #nosec G101
	CollectionPeriodRmmNrMdt_10240 CollectionPeriodRmmNrMdt = "10240" // #nosec G101
	CollectionPeriodRmmNrMdt_60000 CollectionPeriodRmmNrMdt = "60000" // #nosec G101
)
