/*
 * LMF Location
 *
 * LMF Location Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.572 V17.10.0; 5G System; Location Management Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.572/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Lmf_Loc_VelocityRequested string

// List of Lmf_Loc_VelocityRequested
const (
	Lmf_Loc_VelocityRequested_NOT_REQUESTED Lmf_Loc_VelocityRequested = "VELOCITY_IS_NOT_REQUESTED" // #nosec G101
	Lmf_Loc_VelocityRequested_REQUESTED     Lmf_Loc_VelocityRequested = "VELOCITY_IS_REQUESTED"     // #nosec G101
)
