/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.520 V17.9.0; 5G System; Network Data Analytics Services.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Dccf_DataMgmt_SummarizationAttribute string

// List of Dccf_DataMgmt_SummarizationAttribute
const (
	Dccf_DataMgmt_SummarizationAttribute_SPACING     Dccf_DataMgmt_SummarizationAttribute = "SPACING"     // #nosec G101
	Dccf_DataMgmt_SummarizationAttribute_DURATION    Dccf_DataMgmt_SummarizationAttribute = "DURATION"    // #nosec G101
	Dccf_DataMgmt_SummarizationAttribute_OCCURRENCES Dccf_DataMgmt_SummarizationAttribute = "OCCURRENCES" // #nosec G101
	Dccf_DataMgmt_SummarizationAttribute_AVG_VAR     Dccf_DataMgmt_SummarizationAttribute = "AVG_VAR"     // #nosec G101
	Dccf_DataMgmt_SummarizationAttribute_FREQ_VAL    Dccf_DataMgmt_SummarizationAttribute = "FREQ_VAL"    // #nosec G101
	Dccf_DataMgmt_SummarizationAttribute_MIN_MAX     Dccf_DataMgmt_SummarizationAttribute = "MIN_MAX"     // #nosec G101
)
