/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.512 V17.11.0; 5G System; Session Management Policy Control Service.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.512/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Pcf_SMPolCtrl_RequestedRuleDataType string

// List of Pcf_SMPolCtrl_RequestedRuleDataType
const (
	Pcf_SMPolCtrl_RequestedRuleDataType_CH_ID         Pcf_SMPolCtrl_RequestedRuleDataType = "CH_ID"         // #nosec G101
	Pcf_SMPolCtrl_RequestedRuleDataType_MS_TIME_ZONE  Pcf_SMPolCtrl_RequestedRuleDataType = "MS_TIME_ZONE"  // #nosec G101
	Pcf_SMPolCtrl_RequestedRuleDataType_USER_LOC_INFO Pcf_SMPolCtrl_RequestedRuleDataType = "USER_LOC_INFO" // #nosec G101
	Pcf_SMPolCtrl_RequestedRuleDataType_RES_RELEASE   Pcf_SMPolCtrl_RequestedRuleDataType = "RES_RELEASE"   // #nosec G101
	Pcf_SMPolCtrl_RequestedRuleDataType_SUCC_RES_ALLO Pcf_SMPolCtrl_RequestedRuleDataType = "SUCC_RES_ALLO" // #nosec G101
	Pcf_SMPolCtrl_RequestedRuleDataType_EPS_FALLBACK  Pcf_SMPolCtrl_RequestedRuleDataType = "EPS_FALLBACK"  // #nosec G101
)
