/*
 * 3gpp-pfd-management
 *
 * API for PFD management.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.122 V17.10.0 T8 reference point for Northbound APIs
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.122/
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Represents a PFD report indicating the external application identifier(s) which PFD(s) are not
// added or modified successfully and the corresponding failure cause(s).
type Nef_T8PFDMgmt_PfdReport struct {
	// Identifies the external application identifier(s) which PFD(s) are not added or modified
	// successfully
	ExternalAppIds []string `json:"externalAppIds,omitempty" yaml:"externalAppIds,omitempty" bson:"externalAppIds,omitempty"`

	FailureCode Nef_T8PFDMgmt_FailureCode `json:"failureCode,omitempty" yaml:"failureCode,omitempty" bson:"failureCode,omitempty"`

	// Unsigned integer identifying a period of time in units of seconds.
	CachingTime int32 `json:"cachingTime,omitempty" yaml:"cachingTime,omitempty" bson:"cachingTime,omitempty"`

	LocationArea *Nef_T8PFDMgmt_UserPlaneLocationArea `json:"locationArea,omitempty" yaml:"locationArea,omitempty" bson:"locationArea,omitempty"`
}
