/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.520 V17.10.0; 5G System; Network Data Analytics Services.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains analytics metadata information required for analytics aggregation.
type AnalyticsMetadataInfo struct {
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NumSamples    int32                           `json:"numSamples,omitempty" yaml:"numSamples" bson:"numSamples,omitempty"`
	DataWindow    *TimeWindow                     `json:"dataWindow,omitempty" yaml:"dataWindow" bson:"dataWindow,omitempty"`
	DataStatProps []DatasetStatisticalProperty    `json:"dataStatProps,omitempty" yaml:"dataStatProps" bson:"dataStatProps,omitempty"`
	Strategy      OutputStrategy                  `json:"strategy,omitempty" yaml:"strategy" bson:"strategy,omitempty"`
	Accuracy      NwdafEventsSubscriptionAccuracy `json:"accuracy,omitempty" yaml:"accuracy" bson:"accuracy,omitempty"`
}
