/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.512 V17.11.0; 5G System; Session Management Policy Control Service.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.512/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// This data type is defined in the same way as the 'PresenceInfo' data type, but with the OpenAPI 'nullable: true' property.  If the additionalPraId IE is present, this IE shall state the presence information of the UE for the individual PRA identified by the additionalPraId IE;  If the additionalPraId IE is not present, this IE shall state the presence information of the UE for the PRA identified by the praId IE.
type PresenceInfoRm struct {
	// Represents an identifier of the Presence Reporting Area (see clause 28.10 of  3GPP TS 23.003. This IE shall be present  if the Area of Interest subscribed or reported is a Presence Reporting Area or a Set of Core Network predefined Presence Reporting Areas. When present, it shall be encoded as a string representing an integer in the following ranges: - 0 to 8 388 607 for UE-dedicated PRA - 8 388 608 to 16 777 215 for Core Network predefined PRA Examples: PRA ID 123 is encoded as \"123\" PRA ID 11 238 660 is encoded as \"11238660\"
	PraId string `json:"praId,omitempty" yaml:"praId" bson:"praId,omitempty"`
	// This IE may be present if the praId IE is present and if it contains a PRA identifier referring to a set of Core Network predefined Presence Reporting Areas. When present, this IE shall contain a PRA Identifier of an individual PRA within the Set of Core Network predefined Presence Reporting Areas indicated by the praId IE.
	AdditionalPraId string        `json:"additionalPraId,omitempty" yaml:"additionalPraId" bson:"additionalPraId,omitempty"`
	PresenceState   PresenceState `json:"presenceState,omitempty" yaml:"presenceState" bson:"presenceState,omitempty"`
	// Represents the list of tracking areas that constitutes the area. This IE shall be present if the subscription or the event report  is for tracking UE presence in the tracking areas. For non 3GPP access the TAI shall be the N3GPP TAI.
	TrackingAreaList []Tai `json:"trackingAreaList,omitempty" yaml:"trackingAreaList" bson:"trackingAreaList,omitempty"`
	// Represents the list of EUTRAN cell Ids that constitutes the area. This IE shall be present if the Area of Interest subscribed is a list of EUTRAN cell Ids.
	EcgiList []Ecgi `json:"ecgiList,omitempty" yaml:"ecgiList" bson:"ecgiList,omitempty"`
	// Represents the list of NR cell Ids that constitutes the area. This IE shall be present if the Area of Interest subscribed is a list of NR cell Ids.
	NcgiList []Ncgi `json:"ncgiList,omitempty" yaml:"ncgiList" bson:"ncgiList,omitempty"`
	// Represents the list of NG RAN node identifiers that constitutes the area. This IE shall be present if the Area of Interest subscribed is a list of NG RAN node identifiers.
	GlobalRanNodeIdList []GlobalRanNodeId `json:"globalRanNodeIdList,omitempty" yaml:"globalRanNodeIdList" bson:"globalRanNodeIdList,omitempty"`
	// Represents the list of eNodeB identifiers that constitutes the area. This IE shall be present if the Area of Interest subscribed is a list of eNodeB identifiers.
	GlobaleNbIdList []GlobalRanNodeId `json:"globaleNbIdList,omitempty" yaml:"globaleNbIdList" bson:"globaleNbIdList,omitempty"`
}
