/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.518 V17.12.0; 5G System; Access and Mobility Management Services
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SMF derived CN assisted RAN parameters tuning
type CnAssistedRanPara struct {
	StationaryIndication StationaryIndication `json:"stationaryIndication,omitempty" yaml:"stationaryIndication" bson:"stationaryIndication,omitempty"`
	// indicating a time in seconds.
	CommunicationDurationTime int32 `json:"communicationDurationTime,omitempty" yaml:"communicationDurationTime" bson:"communicationDurationTime,omitempty"`
	// indicating a time in seconds.
	PeriodicTime               int32                       `json:"periodicTime,omitempty" yaml:"periodicTime" bson:"periodicTime,omitempty"`
	ScheduledCommunicationTime *ScheduledCommunicationTime `json:"scheduledCommunicationTime,omitempty" yaml:"scheduledCommunicationTime" bson:"scheduledCommunicationTime,omitempty"`
	ScheduledCommunicationType ScheduledCommunicationType  `json:"scheduledCommunicationType,omitempty" yaml:"scheduledCommunicationType" bson:"scheduledCommunicationType,omitempty"`
	TrafficProfile             TrafficProfile              `json:"trafficProfile,omitempty" yaml:"trafficProfile" bson:"trafficProfile,omitempty"`
	BatteryIndication          *BatteryIndication          `json:"batteryIndication,omitempty" yaml:"batteryIndication" bson:"batteryIndication,omitempty"`
}
