/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.502 V17.12.0; 5G System; Session Management Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.502/
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

// Error within Create SM Context Response
type Smf_PDUSess_SmContextCreateError struct {
	Error *Smf_PDUSess_ExtProblemDetails `json:"error,omitempty" yaml:"error,omitempty" bson:"error,omitempty"`

	N1SmMsg *RefToBinaryData `json:"n1SmMsg,omitempty" yaml:"n1SmMsg,omitempty" bson:"n1SmMsg,omitempty"`

	N2SmInfo *RefToBinaryData `json:"n2SmInfo,omitempty" yaml:"n2SmInfo,omitempty" bson:"n2SmInfo,omitempty"`

	N2SmInfoType Smf_PDUSess_N2SmInfoType `json:"n2SmInfoType,omitempty" yaml:"n2SmInfoType,omitempty" bson:"n2SmInfoType,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	RecoveryTime *time.Time `json:"recoveryTime,omitempty" yaml:"recoveryTime,omitempty" bson:"recoveryTime,omitempty"`
}
