/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.512 V17.11.0; 5G System; Session Management Policy Control Service.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.512/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Pcf_SMPolCtrl_RedirectAddressType string

// List of Pcf_SMPolCtrl_RedirectAddressType
const (
	Pcf_SMPolCtrl_RedirectAddressType_IPV4_ADDR Pcf_SMPolCtrl_RedirectAddressType = "IPV4_ADDR" // #nosec G101
	Pcf_SMPolCtrl_RedirectAddressType_IPV6_ADDR Pcf_SMPolCtrl_RedirectAddressType = "IPV6_ADDR" // #nosec G101
	Pcf_SMPolCtrl_RedirectAddressType_URL       Pcf_SMPolCtrl_RedirectAddressType = "URL"       // #nosec G101
	Pcf_SMPolCtrl_RedirectAddressType_SIP_URI   Pcf_SMPolCtrl_RedirectAddressType = "SIP_URI"   // #nosec G101
)
