/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.503 Unified Data Management Services, version 17.14.0
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
 *
 * API version: 2.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Udm_SDM_DataSetName string

// List of Udm_SDM_DataSetName
const (
	Udm_SDM_DataSetName_AM          Udm_SDM_DataSetName = "AM"          // #nosec G101
	Udm_SDM_DataSetName_SMF_SEL     Udm_SDM_DataSetName = "SMF_SEL"     // #nosec G101
	Udm_SDM_DataSetName_UEC_SMF     Udm_SDM_DataSetName = "UEC_SMF"     // #nosec G101
	Udm_SDM_DataSetName_UEC_SMSF    Udm_SDM_DataSetName = "UEC_SMSF"    // #nosec G101
	Udm_SDM_DataSetName_SMS_SUB     Udm_SDM_DataSetName = "SMS_SUB"     // #nosec G101
	Udm_SDM_DataSetName_SM          Udm_SDM_DataSetName = "SM"          // #nosec G101
	Udm_SDM_DataSetName_TRACE       Udm_SDM_DataSetName = "TRACE"       // #nosec G101
	Udm_SDM_DataSetName_SMS_MNG     Udm_SDM_DataSetName = "SMS_MNG"     // #nosec G101
	Udm_SDM_DataSetName_LCS_PRIVACY Udm_SDM_DataSetName = "LCS_PRIVACY" // #nosec G101
	Udm_SDM_DataSetName_LCS_MO      Udm_SDM_DataSetName = "LCS_MO"      // #nosec G101
	Udm_SDM_DataSetName_UEC_AMF     Udm_SDM_DataSetName = "UEC_AMF"     // #nosec G101
	Udm_SDM_DataSetName_V2_X        Udm_SDM_DataSetName = "V2X"         // #nosec G101
	Udm_SDM_DataSetName_LCS_BCA     Udm_SDM_DataSetName = "LCS_BCA"     // #nosec G101
	Udm_SDM_DataSetName_PROSE       Udm_SDM_DataSetName = "PROSE"       // #nosec G101
	Udm_SDM_DataSetName_UC          Udm_SDM_DataSetName = "UC"          // #nosec G101
	Udm_SDM_DataSetName_MBS         Udm_SDM_DataSetName = "MBS"         // #nosec G101
)
