/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 32.291 V16.14.0: Telecommunication management; Charging management;  5G system, charging service; Stage 3.
 * Url: http://www.3gpp.org/ftp/Specs/archive/32_series/32.291/
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains QoS characteristics for a non-standardized or a non-configured 5QI.
type Pcf_SMPolCtrl_QosCharacteristics struct {
	// Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501,
	// within the range 0 to 255.
	Var5qi int32 `json:"5qi,omitempty" yaml:"5qi,omitempty" bson:"5qi,omitempty"`

	ResourceType QosResourceType `json:"resourceType,omitempty" yaml:"resourceType,omitempty" bson:"resourceType,omitempty"`

	// Unsigned integer indicating the 5QI Priority Level (see clauses 5.7.3.3 and 5.7.4 of 3GPP TS
	// 23.501, within the range 1 to 127.Values are ordered in decreasing order of priority,  i.e.
	// with 1 as the highest priority and 127 as the lowest priority.
	PriorityLevel int32 `json:"priorityLevel,omitempty" yaml:"priorityLevel,omitempty" bson:"priorityLevel,omitempty"`

	// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS
	// 23.501), expressed in milliseconds.
	PacketDelayBudget int32 `json:"packetDelayBudget,omitempty" yaml:"packetDelayBudget,omitempty" bson:"packetDelayBudget,omitempty"`

	// String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501,
	// expressed as a \"scalar x 10-k\" where the scalar and the exponent k are each encoded as one
	// decimal digit.
	PacketErrorRate string `json:"packetErrorRate,omitempty" yaml:"packetErrorRate,omitempty" bson:"packetErrorRate,omitempty"`

	// Unsigned integer indicating Averaging Window (see clause 5.7.3.6 and 5.7.4 of 3GPP TS
	// 23.501), expressed in milliseconds.
	AveragingWindow int32 `json:"averagingWindow,omitempty" yaml:"averagingWindow,omitempty" bson:"averagingWindow,omitempty"`

	// Unsigned integer indicating Maximum Data Burst Volume (see clauses 5.7.3.7 and 5.7.4 of 3GPP
	// TS 23.501), expressed in Bytes.
	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty" yaml:"maxDataBurstVol,omitempty" bson:"maxDataBurstVol,omitempty"`

	// Unsigned integer indicating Maximum Data Burst Volume (see clauses 5.7.3.7 and 5.7.4 of 3GPP
	// TS 23.501), expressed in Bytes.
	ExtMaxDataBurstVol int32 `json:"extMaxDataBurstVol,omitempty" yaml:"extMaxDataBurstVol,omitempty" bson:"extMaxDataBurstVol,omitempty"`
}
