/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.514 V17.9.0; 5G System; Policy Authorization Service; Stage 3.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.514/
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Describes the event information delivered in the subscription.
type Pcf_PolAuth_AfRoutingRequirement struct {
	AppReloc bool `json:"appReloc,omitempty" yaml:"appReloc,omitempty" bson:"appReloc,omitempty"`

	RouteToLocs []RouteToLocation `json:"routeToLocs,omitempty" yaml:"routeToLocs,omitempty" bson:"routeToLocs,omitempty"`

	SpVal *Pcf_PolAuth_SpatialValidity `json:"spVal,omitempty" yaml:"spVal,omitempty" bson:"spVal,omitempty"`

	TempVals []Pcf_PolAuth_TemporalValidity `json:"tempVals,omitempty" yaml:"tempVals,omitempty" bson:"tempVals,omitempty"`

	UpPathChgSub *Pcf_SMPolCtrl_UpPathChgEvent `json:"upPathChgSub,omitempty" yaml:"upPathChgSub,omitempty" bson:"upPathChgSub,omitempty"`

	AddrPreserInd bool `json:"addrPreserInd,omitempty" yaml:"addrPreserInd,omitempty" bson:"addrPreserInd,omitempty"`

	// Indicates whether simultaneous connectivity should be temporarily maintained for the source
	// and target PSA.
	SimConnInd bool `json:"simConnInd,omitempty" yaml:"simConnInd,omitempty" bson:"simConnInd,omitempty"`

	// indicating a time in seconds.
	SimConnTerm int32 `json:"simConnTerm,omitempty" yaml:"simConnTerm,omitempty" bson:"simConnTerm,omitempty"`

	// Contains EAS IP replacement information.
	EasIpReplaceInfos []EasIpReplacementInfo `json:"easIpReplaceInfos,omitempty" yaml:"easIpReplaceInfos,omitempty" bson:"easIpReplaceInfos,omitempty"`

	// Indicates the EAS rediscovery is required.
	EasRedisInd bool `json:"easRedisInd,omitempty" yaml:"easRedisInd,omitempty" bson:"easRedisInd,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxAllowedUpLat int32 `json:"maxAllowedUpLat,omitempty" yaml:"maxAllowedUpLat,omitempty" bson:"maxAllowedUpLat,omitempty"`
}
