/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.504 V17.14.0; 5G System; Unified Data Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.504/
 *
 * API version: 2.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Udr_DR_DataSetName string

// List of Udr_DR_DataSetName
const (
	Udr_DR_DataSetName_AM           Udr_DR_DataSetName = "AM"           // #nosec G101
	Udr_DR_DataSetName_SMF_SEL      Udr_DR_DataSetName = "SMF_SEL"      // #nosec G101
	Udr_DR_DataSetName_SMS_SUB      Udr_DR_DataSetName = "SMS_SUB"      // #nosec G101
	Udr_DR_DataSetName_SM           Udr_DR_DataSetName = "SM"           // #nosec G101
	Udr_DR_DataSetName_TRACE        Udr_DR_DataSetName = "TRACE"        // #nosec G101
	Udr_DR_DataSetName_SMS_MNG      Udr_DR_DataSetName = "SMS_MNG"      // #nosec G101
	Udr_DR_DataSetName_LCS_PRIVACY  Udr_DR_DataSetName = "LCS_PRIVACY"  // #nosec G101
	Udr_DR_DataSetName_LCS_MO       Udr_DR_DataSetName = "LCS_MO"       // #nosec G101
	Udr_DR_DataSetName_LCS_BCA      Udr_DR_DataSetName = "LCS_BCA"      // #nosec G101
	Udr_DR_DataSetName_V2_X         Udr_DR_DataSetName = "V2X"          // #nosec G101
	Udr_DR_DataSetName_PROSE        Udr_DR_DataSetName = "PROSE"        // #nosec G101
	Udr_DR_DataSetName_ODB          Udr_DR_DataSetName = "ODB"          // #nosec G101
	Udr_DR_DataSetName_EE_PROF      Udr_DR_DataSetName = "EE_PROF"      // #nosec G101
	Udr_DR_DataSetName_PP_PROF      Udr_DR_DataSetName = "PP_PROF"      // #nosec G101
	Udr_DR_DataSetName_NIDD_AUTH    Udr_DR_DataSetName = "NIDD_AUTH"    // #nosec G101
	Udr_DR_DataSetName_USER_CONSENT Udr_DR_DataSetName = "USER_CONSENT" // #nosec G101
	Udr_DR_DataSetName_MBS          Udr_DR_DataSetName = "MBS"          // #nosec G101
)
