/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.512 V17.11.0; 5G System; Session Management Policy Control Service.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.512/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the rule error reports.
type ErrorReport struct {
	Error *ProblemDetails `json:"error,omitempty" yaml:"error" bson:"error,omitempty"`
	// Used to report the PCC rule failure.
	RuleReports []RuleReport `json:"ruleReports,omitempty" yaml:"ruleReports" bson:"ruleReports,omitempty"`
	// Used to report the session rule failure.
	SessRuleReports []SessionRuleReport `json:"sessRuleReports,omitempty" yaml:"sessRuleReports" bson:"sessRuleReports,omitempty"`
	// Used to report failure of the policy decision and/or condition data.
	PolDecFailureReports []PolicyDecisionFailureCode `json:"polDecFailureReports,omitempty" yaml:"polDecFailureReports" bson:"polDecFailureReports,omitempty"`
	// Indicates the invalid parameters for the reported type(s) of the failed policy decision and/or condition data.
	InvalidPolicyDecs []InvalidParam `json:"invalidPolicyDecs,omitempty" yaml:"invalidPolicyDecs" bson:"invalidPolicyDecs,omitempty"`
}
