/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 32.291 V17.9.0: Telecommunication management; Charging management;  5G system, charging service; Stage 3.
 * Url: http://www.3gpp.org/ftp/Specs/archive/32_series/32.291/
 *
 * API version: 3.1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ServiceProfileChargingInformation struct {
	ServiceProfileIdentifier  string       `json:"serviceProfileIdentifier,omitempty" yaml:"serviceProfileIdentifier" bson:"serviceProfileIdentifier,omitempty"`
	SNSSAIList                []Snssai     `json:"sNSSAIList,omitempty" yaml:"sNSSAIList" bson:"sNSSAIList,omitempty"`
	SST                       int32        `json:"sST,omitempty" yaml:"sST" bson:"sST,omitempty"`
	Latency                   int32        `json:"latency,omitempty" yaml:"latency" bson:"latency,omitempty"`
	Availability              float32      `json:"availability,omitempty" yaml:"availability" bson:"availability,omitempty"`
	ResourceSharingLevel      SharingLevel `json:"resourceSharingLevel,omitempty" yaml:"resourceSharingLevel" bson:"resourceSharingLevel,omitempty"`
	Jitter                    int32        `json:"jitter,omitempty" yaml:"jitter" bson:"jitter,omitempty"`
	Reliability               string       `json:"reliability,omitempty" yaml:"reliability" bson:"reliability,omitempty"`
	MaxNumberofUEs            int32        `json:"maxNumberofUEs,omitempty" yaml:"maxNumberofUEs" bson:"maxNumberofUEs,omitempty"`
	CoverageArea              string       `json:"coverageArea,omitempty" yaml:"coverageArea" bson:"coverageArea,omitempty"`
	DLThptPerSlice            *Throughput  `json:"dLThptPerSlice,omitempty" yaml:"dLThptPerSlice" bson:"dLThptPerSlice,omitempty"`
	DLThptPerUE               *Throughput  `json:"dLThptPerUE,omitempty" yaml:"dLThptPerUE" bson:"dLThptPerUE,omitempty"`
	ULThptPerSlice            *Throughput  `json:"uLThptPerSlice,omitempty" yaml:"uLThptPerSlice" bson:"uLThptPerSlice,omitempty"`
	ULThptPerUE               *Throughput  `json:"uLThptPerUE,omitempty" yaml:"uLThptPerUE" bson:"uLThptPerUE,omitempty"`
	MaxNumberofPDUsessions    int32        `json:"maxNumberofPDUsessions,omitempty" yaml:"maxNumberofPDUsessions" bson:"maxNumberofPDUsessions,omitempty"`
	KPIMonitoringList         string       `json:"kPIMonitoringList,omitempty" yaml:"kPIMonitoringList" bson:"kPIMonitoringList,omitempty"`
	SupportedAccessTechnology int32        `json:"supportedAccessTechnology,omitempty" yaml:"supportedAccessTechnology" bson:"supportedAccessTechnology,omitempty"`
	AddServiceProfileInfo     string       `json:"addServiceProfileInfo,omitempty" yaml:"addServiceProfileInfo" bson:"addServiceProfileInfo,omitempty"`
}
