/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.562 HSS Services for interworking with IMS, version 17.6.0
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.562/
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Indicates changes on a resource.
type NotifyItem struct {
	// String providing an URI formatted according to RFC 3986.
	ResourceId string       `json:"resourceId" yaml:"resourceId" bson:"resourceId,omitempty"`
	Changes    []ChangeItem `json:"changes" yaml:"changes" bson:"changes,omitempty"`
}
