/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 32.291 V17.9.0: Telecommunication management; Charging management;  5G system, charging service; Stage 3.
 * Url: http://www.3gpp.org/ftp/Specs/archive/32_series/32.291/
 *
 * API version: 3.1.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type Chf_ConvCharging_SMSChargingInformation struct {
	OriginatorInfo *Chf_ConvCharging_OriginatorInfo `json:"originatorInfo,omitempty" yaml:"originatorInfo,omitempty" bson:"originatorInfo,omitempty"`

	RecipientInfo []Chf_ConvCharging_RecipientInfo `json:"recipientInfo,omitempty" yaml:"recipientInfo,omitempty" bson:"recipientInfo,omitempty"`

	// String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as
	//  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via  wireline
	// access, with an indication that this address cannot be trusted for regulatory purpose if this
	//  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7
	//  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.
	UserEquipmentInfo string `json:"userEquipmentInfo,omitempty" yaml:"userEquipmentInfo,omitempty" bson:"userEquipmentInfo,omitempty"`

	RoamerInOut Chf_ConvCharging_RoamerInOut `json:"roamerInOut,omitempty" yaml:"roamerInOut,omitempty" bson:"roamerInOut,omitempty"`

	UserLocationinfo *UserLocation `json:"userLocationinfo,omitempty" yaml:"userLocationinfo,omitempty" bson:"userLocationinfo,omitempty"`

	// String with format \"time-numoffset\" optionally appended by \"daylightSavingTime\", where  -
	// \"time-numoffset\" shall represent the time zone adjusted for daylight saving time and be
	// encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  -
	// \"daylightSavingTime\" shall represent the adjustment that has been made and shall be
	// encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.   The example is for 8 hours
	// behind UTC, +1 hour adjustment for Daylight Saving Time.
	UetimeZone string `json:"uetimeZone,omitempty" yaml:"uetimeZone,omitempty" bson:"uetimeZone,omitempty"`

	RATType RatType `json:"rATType,omitempty" yaml:"rATType,omitempty" bson:"rATType,omitempty"`

	SMSCAddress string `json:"sMSCAddress,omitempty" yaml:"sMSCAddress,omitempty" bson:"sMSCAddress,omitempty"`

	SMDataCodingScheme int32 `json:"sMDataCodingScheme,omitempty" yaml:"sMDataCodingScheme,omitempty" bson:"sMDataCodingScheme,omitempty"`

	SMMessageType Chf_ConvCharging_SMMessageType `json:"sMMessageType,omitempty" yaml:"sMMessageType,omitempty" bson:"sMMessageType,omitempty"`

	SMReplyPathRequested Chf_ConvCharging_ReplyPathRequested `json:"sMReplyPathRequested,omitempty" yaml:"sMReplyPathRequested,omitempty" bson:"sMReplyPathRequested,omitempty"`

	SMUserDataHeader string `json:"sMUserDataHeader,omitempty" yaml:"sMUserDataHeader,omitempty" bson:"sMUserDataHeader,omitempty"`

	SMStatus string `json:"sMStatus,omitempty" yaml:"sMStatus,omitempty" bson:"sMStatus,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	SMDischargeTime *time.Time `json:"sMDischargeTime,omitempty" yaml:"sMDischargeTime,omitempty" bson:"sMDischargeTime,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	NumberofMessagesSent int32 `json:"numberofMessagesSent,omitempty" yaml:"numberofMessagesSent,omitempty" bson:"numberofMessagesSent,omitempty"`

	SMServiceType Chf_ConvCharging_SMServiceType `json:"sMServiceType,omitempty" yaml:"sMServiceType,omitempty" bson:"sMServiceType,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	SMSequenceNumber int32 `json:"sMSequenceNumber,omitempty" yaml:"sMSequenceNumber,omitempty" bson:"sMSequenceNumber,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	SMSresult int32 `json:"sMSresult,omitempty" yaml:"sMSresult,omitempty" bson:"sMSresult,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	SubmissionTime *time.Time `json:"submissionTime,omitempty" yaml:"submissionTime,omitempty" bson:"submissionTime,omitempty"`

	SMPriority Chf_ConvCharging_SMPriority `json:"sMPriority,omitempty" yaml:"sMPriority,omitempty" bson:"sMPriority,omitempty"`

	MessageReference string `json:"messageReference,omitempty" yaml:"messageReference,omitempty" bson:"messageReference,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	MessageSize int32 `json:"messageSize,omitempty" yaml:"messageSize,omitempty" bson:"messageSize,omitempty"`

	MessageClass *Chf_ConvCharging_MessageClass `json:"messageClass,omitempty" yaml:"messageClass,omitempty" bson:"messageClass,omitempty"`

	DeliveryReportRequested Chf_ConvCharging_DeliveryReportRequested `json:"deliveryReportRequested,omitempty" yaml:"deliveryReportRequested,omitempty" bson:"deliveryReportRequested,omitempty"`
}
