/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.520 V17.9.0; 5G System; Network Data Analytics Services.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.520/
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Indicate the supported ProSe Capability by the PCF.
type NrfNfManagementProSeCapability struct {
	ProseDirectDiscovey      bool `json:"proseDirectDiscovey,omitempty" yaml:"proseDirectDiscovey" bson:"proseDirectDiscovey,omitempty"`
	ProseDirectCommunication bool `json:"proseDirectCommunication,omitempty" yaml:"proseDirectCommunication" bson:"proseDirectCommunication,omitempty"`
	ProseL2UetoNetworkRelay  bool `json:"proseL2UetoNetworkRelay,omitempty" yaml:"proseL2UetoNetworkRelay" bson:"proseL2UetoNetworkRelay,omitempty"`
	ProseL3UetoNetworkRelay  bool `json:"proseL3UetoNetworkRelay,omitempty" yaml:"proseL3UetoNetworkRelay" bson:"proseL3UetoNetworkRelay,omitempty"`
	ProseL2RemoteUe          bool `json:"proseL2RemoteUe,omitempty" yaml:"proseL2RemoteUe" bson:"proseL2RemoteUe,omitempty"`
	ProseL3RemoteUe          bool `json:"proseL3RemoteUe,omitempty" yaml:"proseL3RemoteUe" bson:"proseL3RemoteUe,omitempty"`
}
