/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 3.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PduSessionChargingInformation struct {
	ChargingId                       int32                       `json:"chargingId,omitempty" yaml:"chargingId" bson:"chargingId" mapstructure:"ChargingId"`
	HomeProvidedChargingId           int32                       `json:"homeProvidedChargingId,omitempty" yaml:"homeProvidedChargingId" bson:"homeProvidedChargingId" mapstructure:"HomeProvidedChargingId"`
	UserInformation                  *UserInformation            `json:"userInformation,omitempty" yaml:"userInformation" bson:"userInformation" mapstructure:"UserInformation"`
	UserLocationinfo                 *UserLocation               `json:"userLocationinfo,omitempty" yaml:"userLocationinfo" bson:"userLocationinfo" mapstructure:"UserLocationinfo"`
	MAPDUNon3GPPUserLocationInfo     *UserLocation               `json:"mAPDUNon3GPPUserLocationInfo,omitempty" yaml:"mAPDUNon3GPPUserLocationInfo" bson:"mAPDUNon3GPPUserLocationInfo" mapstructure:"MAPDUNon3GPPUserLocationInfo"`
	PresenceReportingAreaInformation map[string]PresenceInfo     `json:"presenceReportingAreaInformation,omitempty" yaml:"presenceReportingAreaInformation" bson:"presenceReportingAreaInformation" mapstructure:"PresenceReportingAreaInformation"`
	UetimeZone                       string                      `json:"uetimeZone,omitempty" yaml:"uetimeZone" bson:"uetimeZone" mapstructure:"UetimeZone"`
	PduSessionInformation            *PduSessionInformation      `json:"pduSessionInformation,omitempty" yaml:"pduSessionInformation" bson:"pduSessionInformation" mapstructure:"PduSessionInformation"`
	UnitCountInactivityTimer         int32                       `json:"unitCountInactivityTimer,omitempty" yaml:"unitCountInactivityTimer" bson:"unitCountInactivityTimer" mapstructure:"UnitCountInactivityTimer"`
	RANSecondaryRATUsageReport       *RanSecondaryRatUsageReport `json:"rANSecondaryRATUsageReport,omitempty" yaml:"rANSecondaryRATUsageReport" bson:"rANSecondaryRATUsageReport" mapstructure:"RANSecondaryRATUsageReport"`
}
