/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.531 V17.8.0; 5G System; Network Slice Selection Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.531/
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// This contains the restricted SNssai information per PLMN
type Nssf_NSSAIAvail_RestrictedSnssai struct {
	HomePlmnId *PlmnId `json:"homePlmnId,omitempty" yaml:"homePlmnId,omitempty" bson:"homePlmnId,omitempty"`

	SNssaiList []ExtSnssai `json:"sNssaiList,omitempty" yaml:"sNssaiList,omitempty" bson:"sNssaiList,omitempty"`

	HomePlmnIdList []PlmnId `json:"homePlmnIdList,omitempty" yaml:"homePlmnIdList,omitempty" bson:"homePlmnIdList,omitempty"`

	RoamingRestriction bool `json:"roamingRestriction,omitempty" yaml:"roamingRestriction,omitempty" bson:"roamingRestriction,omitempty"`
}
