/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.512 V17.11.0; 5G System; Session Management Policy Control Service.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.512/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Pcf_SMPolCtrl_MeteringMethod string

// List of Pcf_SMPolCtrl_MeteringMethod
const (
	Pcf_SMPolCtrl_MeteringMethod_DURATION        Pcf_SMPolCtrl_MeteringMethod = "DURATION"        // #nosec G101
	Pcf_SMPolCtrl_MeteringMethod_VOLUME          Pcf_SMPolCtrl_MeteringMethod = "VOLUME"          // #nosec G101
	Pcf_SMPolCtrl_MeteringMethod_DURATION_VOLUME Pcf_SMPolCtrl_MeteringMethod = "DURATION_VOLUME" // #nosec G101
	Pcf_SMPolCtrl_MeteringMethod_EVENT           Pcf_SMPolCtrl_MeteringMethod = "EVENT"           // #nosec G101
)
