/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.503 Unified Data Management Services, version 17.13.0
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the IP-SM-GW Information
type IpSmGwInfo struct {
	IpSmGwRegistration *IpSmGwRegistration `json:"ipSmGwRegistration,omitempty" yaml:"ipSmGwRegistration" bson:"ipSmGwRegistration,omitempty"`
	IpSmGwGuidance     *IpSmGwGuidance     `json:"ipSmGwGuidance,omitempty" yaml:"ipSmGwGuidance" bson:"ipSmGwGuidance,omitempty"`
}
