/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.518 V17.12.0; 5G System; Access and Mobility Management Services
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ReportIntervalNrMdt string

// List of ReportIntervalNrMdt
const (
	ReportIntervalNrMdt__120     ReportIntervalNrMdt = "120"
	ReportIntervalNrMdt__240     ReportIntervalNrMdt = "240"
	ReportIntervalNrMdt__480     ReportIntervalNrMdt = "480"
	ReportIntervalNrMdt__640     ReportIntervalNrMdt = "640"
	ReportIntervalNrMdt__1024    ReportIntervalNrMdt = "1024"
	ReportIntervalNrMdt__2048    ReportIntervalNrMdt = "2048"
	ReportIntervalNrMdt__5120    ReportIntervalNrMdt = "5120"
	ReportIntervalNrMdt__10240   ReportIntervalNrMdt = "10240"
	ReportIntervalNrMdt__20480   ReportIntervalNrMdt = "20480"
	ReportIntervalNrMdt__40960   ReportIntervalNrMdt = "40960"
	ReportIntervalNrMdt__60000   ReportIntervalNrMdt = "60000"
	ReportIntervalNrMdt__360000  ReportIntervalNrMdt = "360000"
	ReportIntervalNrMdt__720000  ReportIntervalNrMdt = "720000"
	ReportIntervalNrMdt__1800000 ReportIntervalNrMdt = "1800000"
	ReportIntervalNrMdt__3600000 ReportIntervalNrMdt = "3600000"
)
