/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 29.504 V16.9.0; 5G System; Unified Data Repository Services; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.504/
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type DrBdtPolicyData struct {
	InterGroupId string `json:"interGroupId,omitempty" yaml:"interGroupId" bson:"interGroupId,omitempty"`
	Supi         string `json:"supi,omitempty" yaml:"supi" bson:"supi,omitempty"`
	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154.
	BdtRefId string  `json:"bdtRefId" yaml:"bdtRefId" bson:"bdtRefId,omitempty"`
	Dnn      string  `json:"dnn,omitempty" yaml:"dnn" bson:"dnn,omitempty"`
	Snssai   *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai,omitempty"`
	ResUri   string  `json:"resUri,omitempty" yaml:"resUri" bson:"resUri,omitempty"`
}
