/*
 * Nudm_UEAU
 *
 * UDM UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 29.503 Unified Data Management Services, version 16.6.0
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AuthenticationInfoRequest struct {
	SupportedFeatures     string                 `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures,omitempty"`
	ServingNetworkName    string                 `json:"servingNetworkName" yaml:"servingNetworkName" bson:"servingNetworkName,omitempty"`
	ResynchronizationInfo *ResynchronizationInfo `json:"resynchronizationInfo,omitempty" yaml:"resynchronizationInfo" bson:"resynchronizationInfo,omitempty"`
	AusfInstanceId        string                 `json:"ausfInstanceId" yaml:"ausfInstanceId" bson:"ausfInstanceId,omitempty"`
	CellCagInfo           []string               `json:"cellCagInfo,omitempty" yaml:"cellCagInfo" bson:"cellCagInfo,omitempty"`
	N5gcInd               bool                   `json:"n5gcInd,omitempty" yaml:"n5gcInd" bson:"n5gcInd,omitempty"`
}
