/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.518 V17.12.0; 5G System; Access and Mobility Management Services
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Represents SEAF data derived from data received from AUSF
type Amf_Comm_SeafData struct {
	NgKsi *Amf_Comm_NgKsi `json:"ngKsi,omitempty" yaml:"ngKsi,omitempty" bson:"ngKsi,omitempty"`

	KeyAmf *Amf_Comm_KeyAmf `json:"keyAmf,omitempty" yaml:"keyAmf,omitempty" bson:"keyAmf,omitempty"`

	Nh string `json:"nh,omitempty" yaml:"nh,omitempty" bson:"nh,omitempty"`

	Ncc int32 `json:"ncc,omitempty" yaml:"ncc,omitempty" bson:"ncc,omitempty"`

	KeyAmfChangeInd bool `json:"keyAmfChangeInd,omitempty" yaml:"keyAmfChangeInd,omitempty" bson:"keyAmfChangeInd,omitempty"`

	KeyAmfHDerivationInd bool `json:"keyAmfHDerivationInd,omitempty" yaml:"keyAmfHDerivationInd,omitempty" bson:"keyAmfHDerivationInd,omitempty"`
}
