/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 29.518 V16.9.0; 5G System; Access and Mobility Management Services
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LocationType string

// List of LocationType
const (
	LocationType_CURRENT_LOCATION               LocationType = "CURRENT_LOCATION"
	LocationType_CURRENT_OR_LAST_KNOWN_LOCATION LocationType = "CURRENT_OR_LAST_KNOWN_LOCATION"
	LocationType_NOTIFICATION_VERIFICATION_ONLY LocationType = "NOTIFICATION_VERIFICATION_ONLY"
	LocationType_DEFERRED_LOCATION              LocationType = "DEFERRED_LOCATION"
)
