/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 3.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type MicoModeIndication string

// List of MICOModeIndication
const (
	MicoModeIndication_MICO_MODE    MicoModeIndication = "MICO_MODE"
	MicoModeIndication_NO_MICO_MODE MicoModeIndication = "NO_MICO_MODE"
)
