/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 29.508 V16.8.0; 5G System; Session Management Event Exposure Service.
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.508/
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type EventSubscription struct {
	Event             SmfEvent               `json:"event" yaml:"event" bson:"event,omitempty"`
	DnaiChgType       DnaiChangeType         `json:"dnaiChgType,omitempty" yaml:"dnaiChgType" bson:"dnaiChgType,omitempty"`
	DddTraDescriptors []DddTrafficDescriptor `json:"dddTraDescriptors,omitempty" yaml:"dddTraDescriptors" bson:"dddTraDescriptors,omitempty"`
	DddStati          []DlDataDeliveryStatus `json:"dddStati,omitempty" yaml:"dddStati" bson:"dddStati,omitempty"`
	AppIds            []string               `json:"appIds,omitempty" yaml:"appIds" bson:"appIds,omitempty"`
}
