/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 3.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GlobalRanNodeId struct {
	PlmnId  *PlmnId `json:"plmnId" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
	N3IwfId string  `json:"n3IwfId,omitempty" yaml:"n3IwfId" bson:"n3IwfId" mapstructure:"N3IwfId"`
	GNbId   *GNbId  `json:"gNbId,omitempty" yaml:"gNbId" bson:"gNbId" mapstructure:"GNbId"`
	NgeNbId string  `json:"ngeNbId,omitempty" yaml:"ngeNbId" bson:"ngeNbId" mapstructure:"NgeNbId"`
	WagfId  string  `json:"wagfId,omitempty" yaml:"wagfId" bson:"wagfId" mapstructure:"WagfId"`
	TngfId  string  `json:"tngfId,omitempty" yaml:"tngfId" bson:"tngfId" mapstructure:"TngfId"`
	Nid     string  `json:"nid,omitempty" yaml:"nid" bson:"nid" mapstructure:"Nid"`
	ENbId   string  `json:"eNbId,omitempty" yaml:"eNbId" bson:"eNbId" mapstructure:"ENbId"`
}
