/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * Source file: 3GPP TS 29.122 V16.9.0 T8 reference point for Northbound APIs
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.122/
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PFDFailureCode string

// List of FailureCode
const (
	FailureCode_MALFUNCTION         FailureCode = "MALFUNCTION"
	FailureCode_RESOURCE_LIMITATION FailureCode = "RESOURCE_LIMITATION"
	FailureCode_SHORT_DELAY         FailureCode = "SHORT_DELAY"
	FailureCode_APP_ID_DUPLICATED   FailureCode = "APP_ID_DUPLICATED"
	FailureCode_PARTIAL_FAILURE     FailureCode = "PARTIAL_FAILURE"
	FailureCode_OTHER_REASON        FailureCode = "OTHER_REASON"
)
